Repository nasa/cFE, pull requests merged in 2020-05, with the labels that each got.

#649 Integration Candidate: 2020-04-22
  README.md
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_shell.c
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/evs/cfe_evs_log.c
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_tbl_events.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
Labels: IC-20200422

#667 Fix #652, cmake-based OSAL config
  cmake/arch_build.cmake
  cmake/sample_defs/default_osconfig.cmake
  cmake/sample_defs/default_osconfig.h
Labels: CCB-Fast Track, code reviewed

#640 Fix #637, Remove old CFE_ARINC653-related tests
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
Labels: CCB-20200429, IC-20200429, code reviewed, enhancement

#645 Fix #484, Deprecate shell output command
  cmake/sample_defs/cpu1_msgids.h
  fsw/cfe-core/src/es/cfe_es_shell.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/inc/cfe_es_msg.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
Labels: CCB-20200429, IC-20200429, code reviewed, deprecate, enhancement

#642 Fix #641, string operations on GCC9
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_cds.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/time_UT.c
  fsw/cfe-core/unit-test/ut_support.c
Labels: CCB-20200429, IC-20200429, bug, code reviewed

#647 Fix #523, SB Subscription report control on separate MID
  cmake/sample_defs/cpu1_msgids.h
  cmake/sample_defs/sample_mission_cfg.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/unit-test/sb_UT.c
Labels: CCB-20200429, IC-20200429, code reviewed, enhancement

#668 Fix #551, Remove duplicate CFE_TIME_Local1HzISR prototype
  fsw/cfe-core/src/time/cfe_time_utils.h
Labels: CCB-20200506, IC-20200429, code reviewed, enhancement

#677 Fix #676, reference to deprecated CFE_SPACECRAFT_ID
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
Labels: CCB-20200506, IC-20200429, bug, code reviewed

#653 Fix #411, rework exception handling in CFE
  cmake/sample_defs/cpu1_platform_cfg.h
  cmake/target/inc/target_config.h
  cmake/target/src/target_config.c
  docs/src/main.dox
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_erlog.c
  fsw/cfe-core/src/es/cfe_es_log.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/es/cfe_es_verify.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/src/inc/cfe_evs_msg.h
  fsw/cfe-core/src/inc/private/cfe_es_erlog_typedef.h
  fsw/cfe-core/src/inc/private/cfe_es_resetdata_typedef.h
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB-20200506, IC-20200429, code reviewed

#674 Fix #618, stubs must not depend on real msgid implementation
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/time_UT.c
  fsw/cfe-core/unit-test/ut_support.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB-20200506, IC-20200429, code reviewed

#669 Fix #661, TBL events update
  fsw/cfe-core/src/inc/cfe_tbl_events.h
Labels: CCB-20200506, IC-20200429, code reviewed

#670 Fix #519, Deprecate CFS/FS time conversion APIs
  fsw/cfe-core/src/inc/cfe_time.h
  fsw/cfe-core/src/time/cfe_time_api.c
  fsw/cfe-core/unit-test/time_UT.c
  fsw/cfe-core/unit-test/time_UT.h
Labels: CCB-20200506, IC-20200429, code reviewed, enhancement

#492 Unit test macros and example use with SB
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/unit-test/ut_support.c
  fsw/cfe-core/unit-test/ut_support.h
Labels: CCB-20200212, CCB-20200422, CCB-20200429, IC-20200429, code reviewed, enhancement, help wanted, unit test

#646 Fix #639, Remove ES_APP_DEBUG functionality
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
Labels: CCB-20200429, IC-20200429, code reviewed, enhancement

#638 Fix #399, Deprecate decompress
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/fs/cfe_fs_decompress.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/fs_UT.h
  fsw/cfe-core/unit-test/ut_fs_zipfile.h
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
Labels: CCB-20200429, IC-20200429, code reviewed, deprecate, enhancement

#648 Fix #559, Resolve doxygen warnings
  cmake/cfe-common.doxyfile.in
  cmake/osal-common.doxyfile.in
  docs/src/cfe_api.dox
  docs/src/cfe_es.dox
  docs/src/cfe_glossary.dox
  docs/src/cfe_sb.dox
  docs/src/main.dox
  fsw/cfe-core/src/es/cfe_es_cds.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_tbl_events.h
  fsw/cfe-core/src/inc/cfe_time.h
  fsw/cfe-core/src/inc/private/cfe_private.h
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/tbl/cfe_tbl_internal.h
  fsw/cfe-core/src/tbl/cfe_tbl_task.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.h
Labels: CCB-20200506, IC-20200429, code reviewed

#695 Fix #491, Add UT macros
  fsw/cfe-core/unit-test/ut_support.c
  fsw/cfe-core/unit-test/ut_support.h
Labels: CCB-20200212, CCB-20200422, CCB-20200429, code reviewed, enhancement

#686 Fix #681, Resolve doxygen warnings for tbl
  fsw/cfe-core/src/tbl/cfe_tbl_internal.h
Labels: CCB-20200513, IC-20200513, code reviewed, docs

#699 Fix #309, Typo in CFE_ES_RestartApp WriteToSysLog
  fsw/cfe-core/src/es/cfe_es_api.c
Labels: CCB-20200513, IC-20200513, code reviewed, enhancement

#685 Fix #684, order of CleanupTaskResources
  fsw/cfe-core/src/es/cfe_es_apps.c
Labels: CCB-20200513, IC-20200513, code reviewed

#688 Fix #687, validate table handle prior to use
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
Labels: CCB-20200513, IC-20200513, code reviewed, enhancement

#698 Fix #693, Utilize UT macros in sb_UT
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
Labels: CCB-20200513, IC-20200513, code reviewed, enhancement, unit test

#673 Fix #657, Add UT_Stub_RegisterContext to CFE_EVS_SendEvent and CFE_ES_WriteToSysLog
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
Labels: CCB-20200506, IC-20200513, code reviewed

#708 Fix #707, Resolve highest MsgID of 0xFFFF bug
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/sb/cfe_sb_priv.h
Labels: CCB-Fast Track, IC-20200513, bug, code reviewed

#691 Fix #679, Alignment warnings in unit test
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: CCB-20200513, IC-20200513, code reviewed

#712 Integration Candidate 2020-05-13
  README.md
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
Labels: IC-20200415
