Repository nasa/cFE, pull requests merged in 2020-03, with the labels that each got.

#504 Fix #487, CFE_TIME_print format fix
  fsw/cfe-core/ut-stubs/ut_time_stubs.c
Labels: CCB - 20200226, IC - 20200304, code reviewed

#505 Fix #358, Add native permissive mode configuration
  cmake/sample_defs/native_osconfig.h
Labels: CCB - 20200226, IC - 20200304, code reviewed, enhancement

#500 Fix #498, Remove obsolete *.mak files
  fsw/cfe-core/src/es/cfe_es.mak
  fsw/cfe-core/src/evs/cfe_evs.mak
  fsw/cfe-core/src/fs/cfe_fs.mak
  fsw/cfe-core/src/make/app-rules.mak
  fsw/cfe-core/src/make/make-rules.mak
  fsw/cfe-core/src/make/table-rules.mak
  fsw/cfe-core/src/sb/cfe_sb.mak
  fsw/cfe-core/src/tbl/cfe_tbl.mak
  fsw/cfe-core/src/time/cfe_time.mak
Labels: CCB - 20200226, IC - 20200304, code reviewed

#544 IC 20200304
  cmake/sample_defs/native_osconfig.h
  fsw/cfe-core/src/es/cfe_es.mak
  fsw/cfe-core/src/evs/cfe_evs.mak
  fsw/cfe-core/src/fs/cfe_fs.mak
  fsw/cfe-core/src/make/app-rules.mak
  fsw/cfe-core/src/make/make-rules.mak
  fsw/cfe-core/src/make/table-rules.mak
  fsw/cfe-core/src/sb/cfe_sb.mak
  fsw/cfe-core/src/tbl/cfe_tbl.mak
  fsw/cfe-core/src/time/cfe_time.mak
  fsw/cfe-core/ut-stubs/ut_time_stubs.c
Labels: CCB - 20200311, IC - 20200304

#458 Use SRC_LOCAL_PATH as single source of truth
  cmake/global_functions.cmake
Labels: CCB - 20200311, code reviewed, docs

#538 Fix #535 and #537, User's guide doxygen issues
  cmake/cfe-usersguide.doxyfile.in
  cmake/mission_build.cmake
  fsw/cfe-core/src/inc/cfe_es.h
Labels: CCB - 20200311, IC - 20200311, code reviewed, docs

#542 Fix #539, build failure in UT stubs with multiple CPUs
  fsw/cfe-core/unit-test/CMakeLists.txt
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
Labels: CCB - 20200311, IC - 20200311, code reviewed

#545 Updated cFE App Developer's Guide
  docs/cFE Application Developers Guide.doc
  docs/cFE Application Developers Guide.md
Labels: CCB - 20200311, code reviewed, docs, enhancement

#563 Integration Candidate - 20200311
  README.md
  cmake/cfe-usersguide.doxyfile.in
  cmake/global_functions.cmake
  cmake/mission_build.cmake
  docs/cFE Application Developers Guide.doc
  docs/cFE Application Developers Guide.md
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/unit-test/CMakeLists.txt
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
Labels: IC - 20200311

#558 Fix #557, OSAL Guide Scrub
  cmake/Makefile.sample
  cmake/cfe-common.doxyfile.in
  cmake/cfe-usersguide.doxyfile.in
  cmake/osal-common.doxyfile.in
  cmake/osalguide.doxyfile.in
  cmake/sample_defs/cpu1_platform_cfg.h
  docs/README_dox_templates.txt
  docs/dox_templates.xml
  docs/src/cfe_es.dox
  docs/src/cfe_evs.dox
  docs/src/cfe_sb.dox
  docs/src/cfe_tbl.dox
  docs/src/cfe_time.dox
  docs/src/cfe_usersguide.dox
  docs/src/ddd_main.dox
  docs/src/main.dox
  docs/src/mnem_maps/cfe_es_cmd_mnem_map
  docs/src/mnem_maps/cfe_es_tlm_mnem_map
  docs/src/mnem_maps/cfe_evs_cmd_mnem_map
  docs/src/mnem_maps/cfe_evs_tlm_mnem_map
  docs/src/mnem_maps/cfe_sb_cmd_mnem_map
  docs/src/mnem_maps/cfe_sb_tlm_mnem_map
  docs/src/mnem_maps/cfe_tbl_cmd_mnem_map
  docs/src/mnem_maps/cfe_tbl_tlm_mnem_map
  docs/src/mnem_maps/cfe_time_cmd_mnem_map
  docs/src/mnem_maps/cfe_time_tlm_mnem_map
  docs/src/osal_fs.dox
  docs/src/osal_timer.dox
  docs/src/osalguide.dox
  docs/src/osalmain.dox
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/evs/cfe_evs.c
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/fs/cfe_fs_decompress.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_evs.h
  fsw/cfe-core/src/inc/cfe_evs_events.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_time.h
  fsw/cfe-core/src/inc/cfe_time_msg.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/time/cfe_time_api.c
  fsw/cfe-core/src/time/cfe_time_tone.c
Labels: CCB - 20200318, IC - 20200318, code reviewed, docs, enhancement

#562 Fix #561, Add branch coverage reporting
  cmake/Makefile.sample
Labels: CCB - 20200318, IC - 20200318, code reviewed, enhancement

#566 Integration Candidate 2020-03-18
  README.md
  cmake/Makefile.sample
  cmake/cfe-common.doxyfile.in
  cmake/cfe-usersguide.doxyfile.in
  cmake/osal-common.doxyfile.in
  cmake/osalguide.doxyfile.in
  cmake/sample_defs/cpu1_platform_cfg.h
  docs/README_dox_templates.txt
  docs/dox_templates.xml
  docs/src/cfe_es.dox
  docs/src/cfe_evs.dox
  docs/src/cfe_sb.dox
  docs/src/cfe_tbl.dox
  docs/src/cfe_time.dox
  docs/src/cfe_usersguide.dox
  docs/src/ddd_main.dox
  docs/src/main.dox
  docs/src/mnem_maps/cfe_es_cmd_mnem_map
  docs/src/mnem_maps/cfe_es_tlm_mnem_map
  docs/src/mnem_maps/cfe_evs_cmd_mnem_map
  docs/src/mnem_maps/cfe_evs_tlm_mnem_map
  docs/src/mnem_maps/cfe_sb_cmd_mnem_map
  docs/src/mnem_maps/cfe_sb_tlm_mnem_map
  docs/src/mnem_maps/cfe_tbl_cmd_mnem_map
  docs/src/mnem_maps/cfe_tbl_tlm_mnem_map
  docs/src/mnem_maps/cfe_time_cmd_mnem_map
  docs/src/mnem_maps/cfe_time_tlm_mnem_map
  docs/src/osal_fs.dox
  docs/src/osal_timer.dox
  docs/src/osalguide.dox
  docs/src/osalmain.dox
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/evs/cfe_evs.c
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/fs/cfe_fs_decompress.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_evs.h
  fsw/cfe-core/src/inc/cfe_evs_events.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_time.h
  fsw/cfe-core/src/inc/cfe_time_msg.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/time/cfe_time_api.c
  fsw/cfe-core/src/time/cfe_time_tone.c
Labels: IC - 20200318
