Repository nasa/cFE, pull requests merged in 2020-11, with the labels that each got.

#968 Fix #967, Update startup script names
  cmake/sample_defs/cpu1_cfe_es_startup.scr
Labels: CCB-20201028, IC-20201103, dependency

#971 Fix #970, strncpy warning
  fsw/cfe-core/src/es/cfe_es_api.c
Labels: CCB-20201028, IC-20201103

#990 Fix #988, add casts on printf calls
  fsw/cfe-core/src/sb/cfe_sb_api.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_hash.c
Labels: CCB-FastTrack, CCB-READY, IC-20201103

#991 Integration Candidate: 2020-11-03
  README.md
  cmake/sample_defs/cpu1_cfe_es_startup.scr
  cmake/sample_defs/sample_mission_cfg.h
  docs/src/cfe_es.dox
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_cds.h
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_verify.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_es_msg.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/unit-test/es_UT.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_hash.c
Labels: IC-20201103

#984 Fix #983 Updated the CFE_MISSION_TIME_DEF_LEAPS to 37 seconds
  cmake/sample_defs/sample_mission_cfg.h
Labels: CCB-20201104, IC-20201110

#980 Fix #973, CFE_MSG_Init clear option removed
  fsw/cfe-core/src/inc/cfe_msg_api.h
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/ut-stubs/ut_msg_stubs.c
  modules/msg/src/cfe_msg_init.c
  modules/msg/unit-test-coverage/test_cfe_msg_ccsdsext.c
  modules/msg/unit-test-coverage/test_cfe_msg_init.c
Labels: CCB-20201104, IC-20201110

#987 Fix #835, build tables for static apps
  cmake/arch_build.cmake
Labels: CCB-20201104, IC-20201110

#1000 Fix #999, Add flags parameter to module load
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB-FastTrack, IC-20201110, dependency

#1013 Fix #1012, Include cfe_private.h in stubs
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
  fsw/cfe-core/ut-stubs/ut_time_stubs.c
Labels: CCB-FastTrack, IC-20201110, dependency, enhancement

#1011 Fix #1010, CFE_ES_RegisterCDSEx stub update
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: CCB-FastTrack, IC-20201110, dependency

#1008 Integration Candidate: 2020-11-10
  README.md
  cmake/arch_build.cmake
  cmake/sample_defs/sample_mission_cfg.h
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/inc/cfe_evs.h
  fsw/cfe-core/src/inc/cfe_msg_api.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
  fsw/cfe-core/ut-stubs/ut_msg_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
  fsw/cfe-core/ut-stubs/ut_time_stubs.c
  modules/msg/src/cfe_msg_init.c
  modules/msg/unit-test-coverage/test_cfe_msg_ccsdsext.c
  modules/msg/unit-test-coverage/test_cfe_msg_init.c
Labels: IC-20201110

#1003 Fix #663, more consistent use of data types
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_cds.c
  fsw/cfe-core/src/es/cfe_es_cds.h
  fsw/cfe-core/src/es/cfe_es_cds_mempool.c
  fsw/cfe-core/src/es/cfe_es_cds_mempool.h
  fsw/cfe-core/src/es/cfe_es_generic_pool.c
  fsw/cfe-core/src/es/cfe_es_generic_pool.h
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/es/cfe_es_perf.c
  fsw/cfe-core/src/es/cfe_es_perf.h
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/evs/cfe_evs_log.c
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/evs/cfe_evs_utils.c
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_es_msg.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_tbl_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_tbl_msg.h
  fsw/cfe-core/src/inc/private/cfe_private.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_buf.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.h
  fsw/cfe-core/src/time/cfe_time_task.c
  fsw/cfe-core/src/time/cfe_time_utils.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/ut_support.c
  fsw/cfe-core/unit-test/ut_support.h
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
Labels: CCB-20201118, IC-20201124, dependency

#998 Fix #777 deprecate sb
  docs/cFE Application Developers Guide.md
  docs/src/cfe_api.dox
  docs/src/cfe_sb.dox
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/evs/cfe_evs_task.h
  fsw/cfe-core/src/evs/cfe_evs_utils.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es_msg.h
  fsw/cfe-core/src/inc/cfe_evs_msg.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_tbl_msg.h
  fsw/cfe-core/src/inc/cfe_time_msg.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.h
  fsw/cfe-core/src/time/cfe_time_task.c
  fsw/cfe-core/src/time/cfe_time_tone.c
  fsw/cfe-core/src/time/cfe_time_utils.c
  fsw/cfe-core/src/time/cfe_time_utils.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/tbl_UT.h
  fsw/cfe-core/unit-test/time_UT.c
  fsw/cfe-core/unit-test/ut_support.c
  fsw/cfe-core/unit-test/ut_support.h
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB-20201104, CCB-FastTrack, CCB: Needs Splinter, IC-20201124, Priority: Mission, conflicts
