Repository nasa/cFE, pull requests merged in 2020-10, with the labels that each got.

#898 Fix #897, EVS unregistered AppID
  fsw/cfe-core/src/evs/cfe_evs_task.h
  fsw/cfe-core/src/evs/cfe_evs_utils.c
Labels: CCB-20200930, IC-202010-07

#925 Fix #923, Perform appid lookup early
  fsw/cfe-core/src/sb/cfe_sb_api.c
Labels: CCB-FastTrack, IC-202010-07

#917 Fix #651, Use resource ID for memory pools
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_generic_pool.c
  fsw/cfe-core/src/es/cfe_es_generic_pool.h
  fsw/cfe-core/src/es/cfe_es_global.h
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/es/cfe_es_mempool.h
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_esmempool.c
  fsw/cfe-core/src/es/cfe_esmempool.h
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
  fsw/cfe-core/unit-test/ut_support.h
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: CCB-20200930, IC-20201007

#899 Fix #705, Use cFE defines to size arrays
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
Labels: CCB-20200930, IC-20201007

#919 Fix #888, Add typedef for function return status codes
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_evs.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_msg_api.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_time.h
Labels: CCB-20200930, IC-20201007

#936 Integration Candidate 2020-10-07
  README.md
  cmake/sample_defs/cpu1_platform_cfg.h
  docs/src/cfe_es.dox
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_generic_pool.c
  fsw/cfe-core/src/es/cfe_es_generic_pool.h
  fsw/cfe-core/src/es/cfe_es_global.h
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/es/cfe_es_mempool.h
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_esmempool.c
  fsw/cfe-core/src/es/cfe_esmempool.h
  fsw/cfe-core/src/evs/cfe_evs_task.h
  fsw/cfe-core/src/evs/cfe_evs_utils.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_evs.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_msg_api.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_time.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
  fsw/cfe-core/unit-test/ut_support.h
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: IC-20201007

#939 Fix #56, Refactor CDS to use generic pool implementation
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_cds.c
  fsw/cfe-core/src/es/cfe_es_cds.h
  fsw/cfe-core/src/es/cfe_es_cds_mempool.c
  fsw/cfe-core/src/es/cfe_es_cds_mempool.h
  fsw/cfe-core/src/es/cfe_es_global.h
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/private/cfe_private.h
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: CCB-20201007, IC-20201007

#941 Fix #940, Add module suffix and core name to configdata
  cmake/target/CMakeLists.txt
  cmake/target/inc/target_config.h
  cmake/target/src/target_config.c
Labels: CCB-FastTrack, CCB-READY, IC-20201013

#856 Apply #853 to Bootes, Set Revision to 99 for development build
  docs/src/cfs_versions.dox
  fsw/cfe-core/src/inc/cfe_version.h
Labels: backport

#946 Fix #943, #924 and #502, improve resource ID management
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_cds.c
  fsw/cfe-core/src/es/cfe_es_cds.h
  fsw/cfe-core/src/es/cfe_es_cds_mempool.c
  fsw/cfe-core/src/es/cfe_es_erlog.c
  fsw/cfe-core/src/es/cfe_es_global.h
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/es/cfe_es_resource.c
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_time.h
  fsw/cfe-core/src/inc/private/cfe_private.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/ut_osprintf_stubs.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: CCB-20201014, IC-20201020

#959 Integration Candidate: 2020-10-20
  README.md
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_cds.c
  fsw/cfe-core/src/es/cfe_es_cds.h
  fsw/cfe-core/src/es/cfe_es_cds_mempool.c
  fsw/cfe-core/src/es/cfe_es_erlog.c
  fsw/cfe-core/src/es/cfe_es_global.h
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/es/cfe_es_resource.c
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_tbl.h
  fsw/cfe-core/src/inc/cfe_time.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/inc/private/cfe_private.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/ut_osprintf_stubs.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: IC-20201020

#947 Fix #928 and #929 - Modularize software bus routing, add msg map hash
  cmake/mission_defaults.cmake
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/inc/cfe_sb_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/inc/private/cfe_sb_destination_typedef.h
  fsw/cfe-core/src/inc/private/cfe_sbr.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/unit-test/CMakeLists.txt
  fsw/cfe-core/unit-test/sb_UT.c
  modules/sbr/CMakeLists.txt
  modules/sbr/private_inc/cfe_sbr_priv.h
  modules/sbr/src/cfe_sbr_map_direct.c
  modules/sbr/src/cfe_sbr_map_hash.c
  modules/sbr/src/cfe_sbr_route_unsorted.c
  modules/sbr/unit-test-coverage/CMakeLists.txt
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_hash.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_route_unsorted.c
Labels: CCB-20201014, CCB-20201021, IC-20201027

#960 Fix #28, provide library API
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/ut_osprintf_stubs.c
Labels: CCB-20201021

#975 Integration Candidate 2020-10-27
  README.md
  cmake/mission_defaults.cmake
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/inc/cfe_sb_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/inc/private/cfe_sb_destination_typedef.h
  fsw/cfe-core/src/inc/private/cfe_sbr.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/unit-test/CMakeLists.txt
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/ut_osprintf_stubs.c
  modules/sbr/CMakeLists.txt
  modules/sbr/private_inc/cfe_sbr_priv.h
  modules/sbr/src/cfe_sbr_map_direct.c
  modules/sbr/src/cfe_sbr_map_hash.c
  modules/sbr/src/cfe_sbr_route_unsorted.c
  modules/sbr/unit-test-coverage/CMakeLists.txt
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_hash.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_route_unsorted.c
Labels: IC-20201027

#977 Fix #976, short background task name
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
Labels: CCB-20201028, IC-20201103

#964 Fix #909, reorganize ES public API + msg definitions
  cmake/sample_defs/sample_mission_cfg.h
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_cds.h
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_verify.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_es_msg.h
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB-20201028, IC-20201103
