Repository nasa/cFE, pull requests merged in 2020-12, with the labels that each got.

#1007 Fix #1006, Refactor UT_SetForceFail to UT_SetDefaultReturnValue
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/time_UT.c
  fsw/cfe-core/unit-test/ut_support.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_map_hash.c
  modules/sbr/unit-test-coverage/test_cfe_sbr_route_unsorted.c
Labels: CCB-20201112, IC-20201124, conflicts, dependency

#1018 Fix #1016, bogus warning in strncpy
  fsw/cfe-core/src/es/cfe_es_apps.c
Labels: CCB-20201118, CCB-FastTrack, IC-20201124

#1024 Fix #1023, correct stub appid parameter
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
  fsw/cfe-core/ut-stubs/ut_time_stubs.c
Labels: CCB-20201118, IC-20201124

#1022 Fix #1004, default stack size
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB-20201118

#1017 Fix #965, remove OSAL ID from App/LibInfo struct
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/inc/cfe_es_msg.h
Labels: CCB-20201118, IC-20201124, conflicts

#1025 Fix #1021, pool buffer type
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_buf.c
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: CCB-20201118, CCB-20201202

#1043 Fix #1042, remove use of osapi-os-loader.h
  fsw/cfe-core/unit-test/es_UT.h
Labels: CCB-20201209, IC-20201215, dependency

#1035 Fix 1034, Atomic type for SystemState
  fsw/cfe-core/src/es/cfe_es_global.h
Labels: CCB-20201209, IC-20201215

#1038 Fix #952, OSAL module flags to permit app reload
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB-20201209

#1046 fix #1030 change test_MSG to UT_DisplayPkt
  modules/msg/unit-test-coverage/CMakeLists.txt
  modules/msg/unit-test-coverage/test_cfe_msg_ccsdsext.c
  modules/msg/unit-test-coverage/test_cfe_msg_ccsdspri.c
  modules/msg/unit-test-coverage/test_cfe_msg_checksum.c
  modules/msg/unit-test-coverage/test_cfe_msg_fc.c
  modules/msg/unit-test-coverage/test_cfe_msg_init.c
  modules/msg/unit-test-coverage/test_cfe_msg_msgid_v1.c
  modules/msg/unit-test-coverage/test_cfe_msg_msgid_v2.c
  modules/msg/unit-test-coverage/test_cfe_msg_time.c
  modules/msg/unit-test-coverage/test_msg_utils.c
  modules/msg/unit-test-coverage/test_msg_utils.h
Labels: CCB-20201216

#1047 cFE Integration candidate: 2020-12-22
  README.md
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_global.h
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
  modules/msg/unit-test-coverage/CMakeLists.txt
  modules/msg/unit-test-coverage/test_cfe_msg_ccsdsext.c
  modules/msg/unit-test-coverage/test_cfe_msg_ccsdspri.c
  modules/msg/unit-test-coverage/test_cfe_msg_checksum.c
  modules/msg/unit-test-coverage/test_cfe_msg_fc.c
  modules/msg/unit-test-coverage/test_cfe_msg_init.c
  modules/msg/unit-test-coverage/test_cfe_msg_msgid_v1.c
  modules/msg/unit-test-coverage/test_cfe_msg_msgid_v2.c
  modules/msg/unit-test-coverage/test_cfe_msg_time.c
  modules/msg/unit-test-coverage/test_msg_utils.c
  modules/msg/unit-test-coverage/test_msg_utils.h
Labels: IC-20201222
