Repository nasa/cFE, pull requests merged in 2020-08, with the labels that each got.

#786 Fix #785, update vxworks 6.9 example toolchain
  cmake/sample_defs/toolchain-ppc-vxworks6.9.cmake
Labels: CCB-20200729, CCB-FastTrack, IC-20200729, bug, code reviewed

#792 Integration Candidate 2020-07-29
  README.md
  cmake/sample_defs/toolchain-ppc-vxworks6.9.cmake
  docs/src/cfs_versions.dox
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/src/time/cfe_time_task.c
Labels: IC-20200729

#779 Fix #778, add cfe assert and example lib
  cmake/mission_defaults.cmake
  modules/cfe_assert/CMakeLists.txt
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_assert/src/cfe_assert_main.c
  modules/cfe_test/CMakeLists.txt
  modules/cfe_test/src/cfe_test.c
  modules/cfe_test/src/cfe_test.h
  modules/cfe_test/src/es_test.c
Labels: CCB-20200729, Priority: Mission, cFS-Caelum, code reviewed

#789 Fix #787, #587, Update requirements
  docs/cFE_FunctionalRequirements.csv
Labels: CCB-20200805, CCB-FastTrack, cFS-Caelum, code reviewed, docs, enhancement

#784 fix #759 - deprecates GetLastSenderId()
  cmake/sample_defs/global_build_options.cmake
  docs/cFE Application Developers Guide.md
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB-20200729, IC-20200812, code reviewed

#805 Revert "Fix #778, add cfe assert and example lib"
  cmake/mission_defaults.cmake
  modules/cfe_assert/CMakeLists.txt
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_assert/src/cfe_assert_main.c
  modules/cfe_test/CMakeLists.txt
  modules/cfe_test/src/cfe_test.c
  modules/cfe_test/src/cfe_test.h
  modules/cfe_test/src/es_test.c
Labels: IC-20200812

#804 Fix #778, Add CFE_Assert library and test module
  cmake/mission_defaults.cmake
  docs/README_functionaltest.md
  modules/cfe_assert/CMakeLists.txt
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_test.c
  modules/cfe_testrunner/CMakeLists.txt
  modules/cfe_testrunner/inc/cfe_testrunner.h
  modules/cfe_testrunner/src/cfe_testrunner_main.c
Labels: IC-20200812, code reviewed

#816 Integration Candidate 2020-08-12
  README.md
  cmake/mission_defaults.cmake
  cmake/sample_defs/global_build_options.cmake
  docs/README_functionaltest.md
  docs/cFE Application Developers Guide.md
  docs/cFE_FunctionalRequirements.csv
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  modules/cfe_assert/CMakeLists.txt
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_test.c
  modules/cfe_testrunner/CMakeLists.txt
  modules/cfe_testrunner/inc/cfe_testrunner.h
  modules/cfe_testrunner/src/cfe_testrunner_main.c
Labels: IC-20200812

#801 Fix #795, Remove legacy time header format support
  cmake/sample_defs/sample_mission_cfg.h
  fsw/cfe-core/src/sb/cfe_sb_verify.h
  modules/msg/CMakeLists.txt
  modules/msg/mission_inc/default_cfe_msg_sechdr.h
  modules/msg/src/cfe_msg_sechdr_time_old.c
Labels: CCB-20200819, CCB-READY, IC-20200819, code reviewed, enhancement

#819 Fix #794, Add msg stubs and update SB UT
  fsw/cfe-core/unit-test/CMakeLists.txt
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/ut-stubs/CMakeLists.txt
  fsw/cfe-core/ut-stubs/ut_msg_stubs.c
Labels: CCB-20200819, CCB-READY, IC-20200819, code reviewed, enhancement, unit test

#838 HOTFIX: Deprecated time format verify logic fix
  fsw/cfe-core/src/sb/cfe_sb_verify.h
Labels: IC-20200819

#840 HOTFIX - no longer add unit tests from within unit tests in msg UT
  modules/msg/unit-test-coverage/msg_UT.c
Labels: IC-20200819

#834 Fix #818, Return message address from CFE_SB_SendMsg stub
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB-20200826, IC-20200826, code reviewed, enhancement, unit test

#799 Fix #798, Remove OS_Milli2Ticks document reference (deprecated)
  docs/cFE Application Developers Guide.md
Labels: IC-20200826, code reviewed, docs, enhancement

#842 Fix #836, Replace CFE_MISSION_SPACECRAFT_ID with CFE_PSP_GetSpacecraftId()
  modules/msg/src/cfe_msg_ccsdsext.c
  modules/msg/unit-test-coverage/test_cfe_msg_ccsdsext.c
Labels: CCB-20200826, IC-20200826, code reviewed, enhancement

#832 Fix #831, Resolve int size mismatch in loop comparison
  fsw/cfe-core/src/sb/cfe_sb_api.c
Labels: CCB-20200826, CCB-FastTrack, IC-20200826, code reviewed

#826 Fix #822, Remove iterator modification in loop
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
Labels: CCB-20200826, CCB-FastTrack, IC-20200826, code reviewed, enhancement

#850 Hotfix IC-20200826: Remove deprecated doxygen references
  docs/src/osalmain.dox
Labels: IC-20200826, code reviewed
