Repository nasa/cFE, pull requests merged in 2020-07, with the labels that each got.

#768 Fix #752, use OS_READ_ONLY, not O_RDONLY
  README.md
  fsw/cfe-core/src/es/cfe_es_apps.c
Labels: CCB-FastTrack, CCB-READY, IC-20200624

#767 Fix #766, Add to table search path
  cmake/arch_build.cmake
Labels: CCB-FastTrack, IC-20200624, Priority: Mission, enhancement

#775 Fix #774, do not generate empty include file
  cmake/global_functions.cmake
Labels: CCB-FastTrack, CCB-READY, IC-20200624

#773 Fix #710, Specify ProcessorID in targets.cmake
  cmake/sample_defs/targets.cmake
  cmake/target/CMakeLists.txt
Labels: CCB-FastTrack, CCB-READY, IC-20200624, Priority: Mission

#765 Integration Candidate: 2020-06-24
  CMakeLists.txt
  README.md
  cmake/Makefile.sample
  cmake/arch_build.cmake
  cmake/cfe-common.doxyfile.in
  cmake/cfe_generated_file.h.in
  cmake/global_functions.cmake
  cmake/mission_build.cmake
  cmake/mission_defaults.cmake
  cmake/osal-common.doxyfile.in
  cmake/sample_defs/targets.cmake
  cmake/target/CMakeLists.txt
  cmake/version.cmake
  docs/src/cfs_versions.dox
  docs/src/main.dox
  fsw/cfe-core/CMakeLists.txt
  fsw/cfe-core/arch_build.cmake
  fsw/cfe-core/mission_build.cmake
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/src/time/cfe_time_task.c
  fsw/cfe-core/unit-test/CMakeLists.txt
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
  fsw/cfe-core/ut-stubs/ut_time_stubs.c
Labels: IC-20200624
