Repository nasa/cFE, pull requests merged in 2020-06, with the labels that each got.

#714 Fix #704, Added stub for CFE_SB_DeletePipe in ut_sb_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB-20200527, IC-20200527, code reviewed

#713 Fix #603, Full context info for EVS event stubs
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
Labels: CCB-20200527, IC-20200527, code reviewed

#725 Fix #719, remove refs to ccsds data structures
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/evs/cfe_evs_task.h
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.h
  fsw/cfe-core/src/time/cfe_time_task.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/time_UT.c
Labels: CCB-Fast Track, IC-20200527, code reviewed, enhancement, ready for CCB

#729 Integration Candidate: 2020-05-27
  README.md
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/evs/cfe_evs_task.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.h
  fsw/cfe-core/src/time/cfe_time_task.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/time_UT.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: IC-20200527

#737 Fix #734, continue cleanup of SB unit test
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/unit-test/ut_support.c
  fsw/cfe-core/unit-test/ut_support.h
Labels: CCB-20200610, IC-20200610, code reviewed

#743 Integration Candidate: 2020-06-10
  README.md
  docs/cFE Application Developers Guide.md
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/unit-test/ut_support.c
  fsw/cfe-core/unit-test/ut_support.h
Labels: IC-20200610

#738 fix #730 - adds null to FILEDEFs
  fsw/cfe-core/src/inc/cfe_tbl_filedef.h
Labels: CCB-20200617, IC-20200617, code reviewed

#742 Fix #604, Added cFE User's Guide Reference to README.md
  README.md
Labels: CCB-FastTrack, IC-20200617, code reviewed, docs, enhancement

#755 Fix #754, Remove obsolete license
  cmake/sample_defs/default_osconfig.cmake
Labels: CCB-FastTrack, CCB-READY, IC-20200617, enhancement

#756 Integration Candidate: 2020-06-17
  README.md
  cmake/sample_defs/default_osconfig.cmake
  fsw/cfe-core/src/inc/cfe_tbl_filedef.h
  fsw/cfe-core/src/inc/cfe_version.h
Labels: IC-20200617
