Repository nasa/cFE, pull requests merged in 2020-04, with the labels that each got.

#533 Fix #532, Link CFE core with OSAL BSP
  cmake/target/CMakeLists.txt
Labels: CCB - 20200325, IC - 20200325, code reviewed

#572 Fix #571, Update App Dev Guide Int Handler
  docs/cFE Application Developers Guide.md
Labels: CCB - 20200401, IC - 20200401, code reviewed, docs, enhancement

#568 Fix #297, CCSDS Command Secondary Header Endian Agnostic
  fsw/cfe-core/src/inc/ccsds.h
  fsw/cfe-core/unit-test/ut_support.c
Labels: CCB - 20200401, IC - 20200401, bug, code reviewed

#570 Fix #569, Resolve CI warnings and add badge
  .travis.yml
  README.md
Labels: CCB - 20200401, IC - 20200401, code reviewed, enhancement

#595 Fix #456, Perf log threading and concurrency issues
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_global.h
  fsw/cfe-core/src/es/cfe_es_perf.c
  fsw/cfe-core/src/es/cfe_es_perf.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/src/inc/private/cfe_es_perfdata_typedef.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
Labels: CCB - Fast Track, IC - 20200401

#586 Integration Candidate - 2020-04-01
  .travis.yml
  README.md
  docs/cFE Application Developers Guide.md
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_global.h
  fsw/cfe-core/src/es/cfe_es_perf.c
  fsw/cfe-core/src/es/cfe_es_perf.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/inc/ccsds.h
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/inc/private/cfe_es_perfdata_typedef.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
  fsw/cfe-core/unit-test/ut_support.c
Labels: IC - 20200401

#593 Fix# 543, Expose CFE_SB_GetPktType
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB - 20200408, code reviewed

#585 Fix #581, Propagate the OSAL compile definitions to CFE build
  cmake/arch_build.cmake
Labels: CCB - 20200408, code reviewed

#574 Fix #573, Update RTEMS example toolchain
  cmake/sample_defs/toolchain-i686-rtems4.11.cmake
Labels: CCB - 20200408, bug, code reviewed

#613 Fix #612, Update coverage compile/link flag options
  fsw/cfe-core/unit-test/CMakeLists.txt
Labels: CCB - Fast Track, IC - 20200408

#615 Integration Candidate 2020-04-08
  README.md
  cmake/arch_build.cmake
  cmake/sample_defs/toolchain-i686-rtems4.11.cmake
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/unit-test/CMakeLists.txt
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: IC - 20200408

#575 Fix #617, Updates comments to note that the length limit of OS_MAX_PATH_LEN and OS_MAX_API_NAME includes null terminator
  cmake/sample_defs/default_osconfig.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_tbl_events.h
Labels: CCB - 20200415, IC - 20200415, code reviewed

#474 CMake: minor changes to improve the CLion IDE CMake experience
  CMakeLists.txt
  cmake/mission_build.cmake
Labels: CCB - 20200415, IC - 20200415, code reviewed

#598 Fix #295, Resolve app table scanning race conditions
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB - 20200415, IC - 20200415, code reviewed

#582 Fix #580, Deprecate CFE_OS_ abstracted error codes
  cmake/sample_defs/global_build_options.cmake
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/unit-test/sb_UT.c
Labels: CCB - 20200415, IC - 20200415, code reviewed, enhancement

#577 Fix #344, Remove mission/platform include dirs
  fsw/mission_inc/cfe_mission_cfg.h
  fsw/mission_inc/cfe_perfids.h
  fsw/platform_inc/cpu1/cfe_msgids.h
  fsw/platform_inc/cpu1/cfe_platform_cfg.h
Labels: CCB - 20200415, IC - 20200415, code reviewed, enhancement

#584 Fix #335: Shell unsigned pkt length bug
  fsw/cfe-core/src/es/cfe_es_shell.c
Labels: CCB - 20200415, IC - 20200415, code reviewed

#605 Fix #494, Updates CFE_SB_GetLastSenderID to check if message has been sent on pipe
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
Labels: CCB - 20200415, IC - 20200415, code reviewed

#634 Fix #632, Infer OSAL_SYSTEM_BSPTYPE from CFE_SYSTEM_PSP_NAME
  cmake/arch_build.cmake
Labels: CCB - 20200422, CCB - Fast Track, IC - 20200415, bug, code reviewed, enhancement

#635 Integration Candidate: 2020-04-15
  CMakeLists.txt
  README.md
  cmake/arch_build.cmake
  cmake/mission_build.cmake
  cmake/sample_defs/default_osconfig.h
  cmake/sample_defs/global_build_options.cmake
  cmake/sample_defs/sample_mission_cfg.h
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_shell.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/evs/cfe_evs_utils.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es_extern_typedefs.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/inc/cfe_tbl_events.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/src/sb/cfe_sb_verify.h
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/src/time/cfe_time_task.c
  fsw/cfe-core/src/time/cfe_time_utils.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/time_UT.c
  fsw/cfe-core/unit-test/ut_support.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
  fsw/mission_inc/cfe_mission_cfg.h
  fsw/mission_inc/cfe_perfids.h
  fsw/platform_inc/cpu1/cfe_msgids.h
  fsw/platform_inc/cpu1/cfe_platform_cfg.h
Labels: IC - 20200415

#625 Fix #410, separate SYSLOG configurable defaults for power on and proc…
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB-20200422, IC-20200422, code reviewed

#619 Fix #591, Avoid deadlock in CFE_ES_CreatObjects
  fsw/cfe-core/src/es/cfe_es_start.c
Labels: CCB-20200422, IC-20200422, code reviewed

#606 Fix #503, better events for CFE_TBL_Load()
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_tbl_events.h
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.h
  fsw/cfe-core/unit-test/tbl_UT.c
Labels: CCB-20200422, IC-20200422, TBL, code reviewed, enhancement

#622 Fix #121, Add check for UsedFlag and sets APID to CFE_TBL_NOT_OWNED
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
Labels: CCB-20200422, IC-20200422, TBL, code reviewed

#624 Fix #623, Replace OS_FS_* return codes with common definitions
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_shell.c
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/evs/cfe_evs_log.c
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
Labels: CCB-20200422, IC-20200422, code reviewed

#654 Fix #652, cmake-based OSAL config
  cmake/arch_build.cmake
  cmake/sample_defs/default_osconfig.cmake
  cmake/sample_defs/default_osconfig.h
Labels: CCB-Fast Track, IC-20200422
