Repository nasa/cFE, pull requests merged in 2020-02, with the labels that each got.

#452 Fix #308, Improve SB create pipe error reporting
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
Labels: code reviewed

#495 Fix #489, Add usersguide/osalguide to local targets
  cmake/Makefile.sample
Labels: CCB - Fast Track, IC - 20200212, enhancement

#511 Integration Candidate 20200212
  README.md
  cmake/Makefile.sample
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB - 20200212, IC - 20200212

#461 Fix #315, ES Performance debug messages
  fsw/cfe-core/src/es/cfe_es_perf.c
Labels: CCB - 20200212, IC - 20200226, code reviewed

#477 Fix #408, Remove device driver references in code
  docs/src/cfe_es.dox
  docs/src/main.dox
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
Labels: CCB - 20200212, IC - 20200226, code reviewed

#485 Fix #274, NumOfChildTasks not decremented
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB - 20200212, IC - 20200226, code reviewed

#510 Fix #509, Executive Services Requirements Scrub
  docs/cFE_FunctionalRequirements.csv
Labels: CCB - 20200212, IC - 20200226, code reviewed, enhancement

#497 Fix #377, Remove device driver requirements
  docs/cFE_FunctionalRequirements.csv
Labels: CCB - 20200212, IC - 20200226, code reviewed, enhancement

#507 Fix #506 - Update API documentation
  docs/src/main.dox
Labels: CCB - 20200212, IC - 20200226, enhancement, ready for CCB

#526 Fix #525, Message Requirements Scrub
  docs/cFE_FunctionalRequirements.csv
Labels: CCB - 20200226, IC - 20200226, code reviewed, enhancement, ready for CCB

#530 IC - 20200226
  README.md
  docs/cFE_FunctionalRequirements.csv
  docs/src/cfe_es.dox
  docs/src/main.dox
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_perf.c
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/es_UT.h
Labels: CCB - 20200226, IC - 20200226, code reviewed
