Repository nasa/cFE, pull requests merged in 2021-07, with the labels that each got.

#1637 Fix #467, #1636 Complete coverage for cfe_es_start.c and cfe_es_syslog.c
  modules/es/fsw/src/cfe_es_log.h
  modules/es/fsw/src/cfe_es_syslog.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1654 cFE Integration candidate: 2021-06-29
  README.md
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/core_api/fsw/inc/cfe_version.h
  modules/core_private/ut-stubs/src/ut_support.c
  modules/es/fsw/src/cfe_es_log.h
  modules/es/fsw/src/cfe_es_syslog.c
  modules/es/ut-coverage/es_UT.c
Labels: community

#1656 Fix #1655, Size unit test table load buffer based on config
  modules/tbl/ut-coverage/tbl_UT.c
Labels: CCB:Approved

#1657 Fix #1651, Add SB Pipe Management Functional Tests.
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/sb_pipe_mang_test.c
Labels: CCB:Approved

#1660 Fix #1635, Change CI to use Test Log.
  .github/workflows/functional-tests.yml
Labels: CCB:Approved

#1664 Fix #1662, remove default .dat extension
  modules/fs/fsw/src/cfe_fs_api.c
  modules/fs/ut-coverage/fs_UT.c
Labels: CCB:Approved

#1670 Fix #1646, Update API doxygen list
  docs/src/cfe_api.dox
Labels: CCB:Ready

#1671 Fix #1606, update documentation for CFE_ES_GetPoolBufInfo
  docs/cFE Application Developers Guide.md
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:Ready

#1674 Fix #1667, CFE_SB_MsgHdrSize returns size_t but still attempts to ret…
  modules/core_api/fsw/inc/cfe_sb.h
  modules/sb/fsw/src/cfe_sb_priv.h
  modules/sb/fsw/src/cfe_sb_util.c
Labels: CCB:Ready

#1668 Fix #471, improve SB coverage test
  modules/sb/ut-coverage/sb_UT.c
  modules/sb/ut-coverage/sb_UT.h
Labels: CCB:Ready

#1694 Fix #1693, correct function name in UT_BSP_Unlock
  modules/cfe_assert/src/cfe_assert_io.c
Labels: CCB:Ready

#1699 Fix #1698, correct return code check
  modules/es/fsw/src/cfe_es_start.c
Labels: CCB:Approved

#1700 Fix #1599, documentation for FS APIs that return OSAL codes
  modules/core_api/fsw/inc/cfe_fs.h
Labels: CCB:Approved

#1695 Fix #469, Adding coverage tests for cfe_es_apps.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1673 Fix #1650, Add File Utility Functional Tests.
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/fs_util_test.c
Labels: CCB:Ready

#1711 Fix #1659, Add custom epoch support to TIME UT
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Ready

#1720 Fix #1702 #1709 #1713 #1717, Requirements update for Caelum
  docs/cFE_FunctionalRequirements.csv
Labels: CCB:Approved

#1721 Fix #1718, Add null check to CFE_ES_TaskID_ToIndex.
  modules/es/fsw/src/cfe_es_api.c
Labels: CCB:Approved

#1719 Fix #1396, scrub command documentation
  docs/cFE Application Developers Guide.md
  docs/src/cfe_es.dox
  docs/src/cfe_evs.dox
  docs/src/cfe_sb.dox
  docs/src/cfe_tbl.dox
  docs/src/cfe_time.dox
  modules/es/fsw/inc/cfe_es_msg.h
  modules/evs/fsw/inc/cfe_evs_msg.h
  modules/sb/fsw/inc/cfe_sb_msg.h
  modules/tbl/fsw/inc/cfe_tbl_msg.h
  modules/time/fsw/inc/cfe_time_msg.h
Labels: CCB:Approved

#1715 Fix #1689, Add time arithmetic functional tests
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/time_arithmetic_test.c
Labels: CCB:Approved

#1704 Fix #1703, update docs for CFE_FS_BackgroundFileDumpRequest
  modules/core_api/fsw/inc/cfe_fs.h
  modules/core_api/fsw/inc/cfe_fs_api_typedefs.h
Labels: CCB:Ready

#1706 Fix #1705, correct return code mismatches
  modules/cfe_assert/src/cfe_assert_io.c
  modules/es/fsw/src/cfe_es_backgroundtask.c
  modules/es/fsw/src/cfe_es_cds.c
  modules/es/fsw/src/cfe_es_task.c
  modules/evs/fsw/src/cfe_evs_log.c
  modules/time/fsw/src/cfe_time_task.c
Labels: CCB:Ready
