Repository nasa/cFE, pull requests merged in 2021-05, with the labels that each got.

#1418 Fix #810, add ES CDS Functional test
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_cds_test.c
Labels: CCB:Approved, IC:2021-05-04

#1414 Fix #1297, fs header functional tests
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/fs_header_test.c
Labels: CCB:Approved, IC:2021-05-04

#1437 Fix #1436, table object file name
  cmake/arch_build.cmake
  cmake/generate_table.cmake
Labels: CCB:Approved, IC:2021-05-11

#1492 cFE Integration candidate: 2021-05-11
  .github/workflows/static-analysis.yml
  .travis.yml
  README.md
  cmake/arch_build.cmake
  cmake/generate_table.cmake
  cmake/sample_defs/default_osconfig.cmake
  cmake/sample_defs/native_osconfig.cmake
  modules/core_api/fsw/inc/cfe_fs.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/core_api/ut-stubs/CMakeLists.txt
  modules/core_api/ut-stubs/src/cfe_es_handlers.c
  modules/core_api/ut-stubs/src/cfe_es_stubs.c
  modules/core_api/ut-stubs/src/cfe_evs_handlers.c
  modules/core_api/ut-stubs/src/cfe_evs_stubs.c
  modules/core_api/ut-stubs/src/cfe_fs_handlers.c
  modules/core_api/ut-stubs/src/cfe_fs_stubs.c
  modules/core_api/ut-stubs/src/cfe_msg_handlers.c
  modules/core_api/ut-stubs/src/cfe_msg_stubs.c
  modules/core_api/ut-stubs/src/cfe_resourceid_handlers.c
  modules/core_api/ut-stubs/src/cfe_resourceid_stubs.c
  modules/core_api/ut-stubs/src/cfe_sb_handlers.c
  modules/core_api/ut-stubs/src/cfe_sb_stubs.c
  modules/core_api/ut-stubs/src/cfe_tbl_handlers.c
  modules/core_api/ut-stubs/src/cfe_tbl_stubs.c
  modules/core_api/ut-stubs/src/cfe_time_handlers.c
  modules/core_api/ut-stubs/src/cfe_time_stubs.c
  modules/core_api/ut-stubs/src/ut_es_stubs.c
  modules/core_api/ut-stubs/src/ut_evs_stubs.c
  modules/core_api/ut-stubs/src/ut_fs_stubs.c
  modules/core_api/ut-stubs/src/ut_msg_stubs.c
  modules/core_api/ut-stubs/src/ut_resourceid_stubs.c
  modules/core_api/ut-stubs/src/ut_sb_stubs.c
  modules/core_api/ut-stubs/src/ut_tbl_stubs.c
  modules/core_api/ut-stubs/src/ut_time_handlers.c
  modules/core_api/ut-stubs/src/ut_time_stubs.c
  modules/core_private/fsw/inc/cfe_es_core_internal.h
  modules/core_private/fsw/inc/cfe_evs_core_internal.h
  modules/core_private/fsw/inc/cfe_fs_core_internal.h
  modules/core_private/fsw/inc/cfe_sb_core_internal.h
  modules/core_private/fsw/inc/cfe_sbr.h
  modules/core_private/fsw/inc/cfe_tbl_core_internal.h
  modules/core_private/fsw/inc/cfe_time_core_internal.h
  modules/core_private/ut-stubs/CMakeLists.txt
  modules/core_private/ut-stubs/src/cfe_es_core_internal_handlers.c
  modules/core_private/ut-stubs/src/cfe_es_core_internal_stubs.c
  modules/core_private/ut-stubs/src/cfe_evs_core_internal_stubs.c
  modules/core_private/ut-stubs/src/cfe_fs_core_internal_handlers.c
  modules/core_private/ut-stubs/src/cfe_fs_core_internal_stubs.c
  modules/core_private/ut-stubs/src/cfe_sb_core_internal_stubs.c
  modules/core_private/ut-stubs/src/cfe_tbl_core_internal_stubs.c
  modules/core_private/ut-stubs/src/cfe_time_core_internal_stubs.c
  modules/core_private/ut-stubs/src/ut_support.c
  modules/es/fsw/src/cfe_es_backgroundtask.c
Labels: IC:2021-05-11

#1482 Fix #1419, Resolve sequence count auto-increment rollover bug
  modules/core_api/fsw/inc/cfe_msg.h
  modules/core_api/ut-stubs/src/cfe_msg_handlers.c
  modules/core_api/ut-stubs/src/cfe_msg_stubs.c
  modules/msg/fsw/src/cfe_msg_ccsdspri.c
  modules/msg/ut-coverage/test_cfe_msg_ccsdspri.c
  modules/sb/ut-coverage/sb_UT.c
  modules/sbr/fsw/src/cfe_sbr_route_unsorted.c
  modules/sbr/ut-coverage/test_cfe_sbr_route_unsorted.c
Labels: CCB:Approved

#1491 Fix #1421, Correctly format code block section terminator
  docs/cFE Application Developers Guide.md
Labels: CCB:Approved, IC:2021-05-18, community, docs

#1530 Fix #1550, typos in developer guide
  docs/cFE Application Developers Guide.md
Labels: CCB:FastTrack, CCB:Ready, IC:2021-05-18, community, docs

#1508 cFE Integration candidate: 2021-05-18
  README.md
  docs/cFE Application Developers Guide.md
  modules/core_api/fsw/inc/cfe_msg.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/core_api/ut-stubs/src/cfe_msg_handlers.c
  modules/core_api/ut-stubs/src/cfe_msg_stubs.c
  modules/msg/fsw/src/cfe_msg_ccsdspri.c
  modules/msg/ut-coverage/test_cfe_msg_ccsdspri.c
  modules/sb/ut-coverage/sb_UT.c
  modules/sbr/fsw/src/cfe_sbr_route_unsorted.c
  modules/sbr/ut-coverage/test_cfe_sbr_route_unsorted.c
Labels: IC:2021-05-18, community

#1524 Fix #1522, add printf format casts
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/time_current_test.c
Labels: CCB:Approved, CCB:Ready, IC:2021-05-25

#1520 Fix #1505, accept "NULL" as entry point
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved, IC:2021-05-25

#1549 Fix #1538, add capability to generate multiple tables
  cmake/arch_build.cmake
  cmake/generate_table.cmake
Labels: CCB:Approved, IC:2021-05-25, build-system

#1551 Fix #1474, #1552, Resolve API prototype/implementation discrepancies
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_evs.h
  modules/core_api/fsw/inc/cfe_msg.h
  modules/core_api/fsw/inc/cfe_resourceid.h
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/fsw/inc/cfe_tbl.h
  modules/core_api/ut-stubs/src/cfe_es_stubs.c
  modules/core_api/ut-stubs/src/cfe_evs_stubs.c
  modules/core_api/ut-stubs/src/cfe_msg_stubs.c
  modules/core_api/ut-stubs/src/cfe_sb_stubs.c
  modules/core_api/ut-stubs/src/ut_time_handlers.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_mempool.c
  modules/evs/fsw/src/cfe_evs.c
  modules/fs/fsw/src/cfe_fs_api.c
  modules/msg/fsw/src/cfe_msg_ccsdsext.c
  modules/msg/fsw/src/cfe_msg_ccsdspri.c
  modules/msg/fsw/src/cfe_msg_init.c
  modules/msg/fsw/src/cfe_msg_msgid_shared.c
  modules/msg/fsw/src/cfe_msg_msgid_v1.c
  modules/msg/fsw/src/cfe_msg_msgid_v2.c
  modules/msg/fsw/src/cfe_msg_sechdr_checksum.c
  modules/msg/fsw/src/cfe_msg_sechdr_fc.c
  modules/msg/fsw/src/cfe_msg_sechdr_time.c
  modules/sb/fsw/src/cfe_sb_api.c
  modules/tbl/fsw/src/cfe_tbl_api.c
  modules/time/fsw/src/cfe_time_api.c
Labels: CCB:Approved, community

#1580 Fix #1364, Update ES verify errors to match test
  modules/es/fsw/src/cfe_es_verify.h
Labels: CCB:Approved, CCB:FastTrack

#1578 Fix #1366, Resolve mismatched endforeach of CMakeList.txt
  CMakeLists.txt
Labels: CCB:Approved, CCB:FastTrack

#1579 Fix #1390, Improve event filter documentation
  modules/core_api/fsw/inc/cfe_evs.h
  modules/core_api/fsw/inc/cfe_evs_api_typedefs.h
Labels: CCB:Approved, CCB:FastTrack

#1576 Fix #1391, EVS/FS documentation cleanup
  modules/core_api/fsw/inc/cfe_fs.h
  modules/core_api/fsw/inc/cfe_fs_extern_typedefs.h
  modules/core_private/fsw/inc/cfe_evs_log_typedef.h
  modules/evs/fsw/src/cfe_evs_task.c
Labels: CCB:Approved, CCB:FastTrack

#1575 Fix #1394, Remove shell file subtype and clarify scope
  modules/core_api/fsw/inc/cfe_fs_extern_typedefs.h
Labels: CCB:Approved, CCB:FastTrack

#1582 Fix #1362, Simplify CFE_ES_QueryAllCmd file open logic
  modules/es/fsw/src/cfe_es_task.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1567 Fix #1423, Remove deprecated elements
  modules/core_api/fsw/inc/cfe_error.h
  modules/core_api/fsw/inc/cfe_sb_api_typedefs.h
Labels: CCB:Approved, CCB:FastTrack

#1556 Fix #1441, Replace Header Content Type magic number.
  modules/fs/fsw/src/cfe_fs_api.c
Labels: CCB:Approved, CCB:FastTrack

#1553 Fix #1446, Remove unused EVS LogMode defines
  modules/evs/fsw/inc/cfe_evs_events.h
  modules/evs/fsw/inc/cfe_evs_msg.h
Labels: CCB:Approved, CCB:FastTrack

#1565 Fix #1455, Add CFE_SB_DestinationD tag and use for pointers
  modules/core_private/fsw/inc/cfe_sb_destination_typedef.h
Labels: CCB:Approved, CCB:FastTrack

#1564 Fix #1476, Use CFE_MSG_SequenceCount_t for seqcnt type
  modules/sbr/fsw/src/cfe_sbr_route_unsorted.c
Labels: CCB:Approved, CCB:FastTrack

#1562 Fix #1485, Document CFE_ES_PoolCreateEx NumBlockSizes error handling
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:Approved, CCB:FastTrack

#1560 Fix #1494, Documentation cleanup in TBL/TIME
  modules/core_api/fsw/inc/cfe_tbl.h
  modules/core_api/fsw/inc/cfe_time.h
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.h
  modules/tbl/fsw/src/cfe_tbl_verify.h
  modules/time/fsw/src/cfe_time_tone.c
Labels: CCB:Approved, CCB:FastTrack

#1558 Fix #1507, Document TblName as app specific
  modules/core_api/fsw/inc/cfe_tbl.h
  modules/tbl/fsw/src/cfe_tbl_api.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_internal.h
Labels: CCB:Approved, CCB:FastTrack

#1563 Fix #1561, use OSAL script to generate API guide
  cmake/Makefile.sample
  cmake/mission_build.cmake
  cmake/osal-common.doxyfile.in
  cmake/osalguide.doxyfile.in
  docs/src/osal_fs.dox
  docs/src/osal_timer.dox
  docs/src/osalmain.dox
Labels: CCB:Approved
