Repository nasa/cFE, pull requests merged in 2021-03, with the labels that each got.

#1154 Fix #1020, refactor SB buffer descriptor object
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_buf.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
Labels: CCB:2021-02-17, Priority: Mission

#1179 Fix #1149, remove cfeesugshellsrv from user guide
  docs/src/cfe_es.dox
Labels: CCB:2021-02-24, IC:2021-03-02

#1140 Fix #546 #547, api argument validation
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/evs/cfe_evs.c
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/time/cfe_time_api.c
Labels: CCB:2021-02-17, CCB:2021-02-24, IC:2021-03-02

#1156 Fix #981, implement better filename parser
  cmake/sample_defs/cpu1_cfe_es_startup.scr
  cmake/sample_defs/cpu1_platform_cfg.h
  cmake/target/inc/target_config.h
  cmake/target/src/target_config.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/fs_UT.h
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
Labels: CCB:2021-02-17, IC:2021-03-02

#1178 Fix #1153, Remove logic based on LogEnabled status
  fsw/cfe-core/src/evs/cfe_evs_log.c
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_evs_events.h
  fsw/cfe-core/unit-test/evs_UT.c
Labels: CCB:2021-02-24, IC:2021-03-02, conflicts

#1197 Fix #1189, correct compiler warnings
  fsw/cfe-core/src/inc/private/cfe_sbr.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  modules/sbr/private_inc/cfe_sbr_priv.h
Labels: CCB:2021-03-03, CCB:FastTrack, IC:2021-03-02

#1196 cFE Integration candidate: 2021-03-02
  README.md
  cmake/sample_defs/cpu1_cfe_es_startup.scr
  cmake/sample_defs/cpu1_platform_cfg.h
  cmake/target/inc/target_config.h
  cmake/target/src/target_config.c
  docs/src/cfe_es.dox
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/evs/cfe_evs.c
  fsw/cfe-core/src/evs/cfe_evs_log.c
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_evs_events.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/inc/private/cfe_sbr.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_buf.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_util.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/time/cfe_time_api.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/fs_UT.h
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
  modules/sbr/private_inc/cfe_sbr_priv.h
Labels: IC:2021-03-02

#1225 Fix #1224, reinstate recipes for coverage test
  modules/core_private/fsw/inc/cfe_time_resetvars_typedef.h
  modules/core_private/ut-stubs/src/ut_support.c
  modules/es/ut-coverage/CMakeLists.txt
  modules/es/ut-coverage/es_UT.h
  modules/evs/ut-coverage/CMakeLists.txt
  modules/evs/ut-coverage/evs_UT.h
  modules/fs/ut-coverage/CMakeLists.txt
  modules/fs/ut-coverage/fs_UT.h
  modules/sb/ut-coverage/CMakeLists.txt
  modules/sb/ut-coverage/sb_UT.h
  modules/tbl/ut-coverage/CMakeLists.txt
  modules/tbl/ut-coverage/tbl_UT.h
  modules/time/fsw/src/cfe_time_utils.h
  modules/time/ut-coverage/CMakeLists.txt
  modules/time/ut-coverage/time_UT.h
Labels: CCB:FastTrack, CCB:Ready

#1218 Fix #1217, bit order macros
  modules/core_api/fsw/inc/cfe_endian.h
Labels: IC:2021-03-23

#1193 Fix #1033, remove false child tasks statement.
  docs/cFE Application Developers Guide.md
Labels: IC:2021-03-23

#1235 Fix #1195, Avoid implicit conversion from vsnprintf errors
  modules/evs/fsw/src/cfe_evs_utils.c
Labels: CCB:2021-03-17, IC:2021-03-23

#1220 Fix #590, Clarify the documentation on SB MsgId
  docs/cFE Application Developers Guide.md
Labels: CCB:Ready

#1230 Fix #1208, Cast isspace input to unsigned char
  modules/es/fsw/src/cfe_es_syslog.c
Labels: CCB:2021-03-17, IC:2021-03-23

#1231 Fix #1204, Use mask instead of cast to alter value
  modules/msg/fsw/src/cfe_msg_msgid_v1.c
Labels: CCB:2021-03-17, IC:2021-03-23

#1232 Fix #1200, Resolve type issues with CFE_ES_FileWriteByteCntErr and CFE_TBL_FindTableInRegistry
  modules/es/fsw/src/cfe_es_task.c
  modules/es/fsw/src/cfe_es_task.h
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/ut-coverage/tbl_UT.c
Labels: CCB:2021-03-17, IC:2021-03-23

#1228 Fix #1221, Use quotes for local includes
  cmake/target/inc/target_config.h
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testrunner/inc/cfe_testrunner.h
  modules/cfe_testrunner/src/cfe_testrunner_main.c
  modules/core_api/fsw/inc/cfe_tbl_filedef.h
  modules/core_private/fsw/inc/cfe_es_erlog_typedef.h
  modules/core_private/fsw/inc/cfe_es_perfdata_typedef.h
  modules/core_private/fsw/inc/cfe_es_resetdata_typedef.h
  modules/core_private/fsw/inc/cfe_evs_log_typedef.h
Labels: CCB:2021-03-17, IC:2021-03-23

#1227 Fix #1226, Add Contributing Guide
  CONTRIBUTING.md
Labels: CCB:FastTrack, docs

#1243 cFE Integration candidate: 2021-03-23
  CONTRIBUTING.md
  README.md
  cmake/target/inc/target_config.h
  docs/cFE Application Developers Guide.md
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testrunner/inc/cfe_testrunner.h
  modules/cfe_testrunner/src/cfe_testrunner_main.c
  modules/core_api/fsw/inc/cfe_endian.h
  modules/core_api/fsw/inc/cfe_tbl_filedef.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/core_private/fsw/inc/cfe_es_erlog_typedef.h
  modules/core_private/fsw/inc/cfe_es_perfdata_typedef.h
  modules/core_private/fsw/inc/cfe_es_resetdata_typedef.h
  modules/core_private/fsw/inc/cfe_evs_log_typedef.h
  modules/es/fsw/src/cfe_es_syslog.c
  modules/es/fsw/src/cfe_es_task.c
  modules/es/fsw/src/cfe_es_task.h
  modules/evs/fsw/src/cfe_evs_utils.c
  modules/msg/fsw/src/cfe_msg_msgid_v1.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/ut-coverage/tbl_UT.c
Labels: IC:2021-03-23

#1237 Fix #1180, Remove impossible conditions
  modules/es/fsw/src/cfe_es_apps.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
Labels: CCB:FastTrack, IC:2021-03-30

#1240 Fix #1002, Remove deprecated elements
  modules/core_api/fsw/inc/cfe_error.h
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/fsw/inc/cfe_sb_api_typedefs.h
  modules/core_api/ut-stubs/src/ut_sb_stubs.c
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_msg_id_util.c
  modules/sb/fsw/src/cfe_sb_priv.c
  modules/sb/fsw/src/cfe_sb_util.c
Labels: CCB:FastTrack, IC:2021-03-30

#1253 Fix #1252, Squash potentially uninitialized variable warnings
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_task.c
  modules/evs/fsw/src/cfe_evs_log.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/msg/fsw/src/cfe_msg_msgid_shared.c
  modules/sb/fsw/src/cfe_sb_task.c
Labels: CCB:FastTrack, IC:2021-03-30

#1241 Fix #1185, Squash possible uninitialized variable false alarms
  modules/es/fsw/src/cfe_es_apps.c
  modules/sb/fsw/src/cfe_sb_api.c
  modules/time/fsw/src/cfe_time_api.c
Labels: CCB:FastTrack

#1247 Fix #1246, Typo in CFE_TBL_Validate AppName
  modules/tbl/fsw/src/cfe_tbl_api.c
Labels: CCB:FastTrack, IC:2021-03-30

#1234 Fix #1192, Initialize TotalMsgSize in CFE_SB_GetUserDataLength
  modules/sb/fsw/src/cfe_sb_util.c
Labels: CCB:FastTrack, IC:2021-03-30

#1245 Fix #1187, Increment CreatePipeErrorCounter for all create pipe errors
  modules/sb/fsw/src/cfe_sb_api.c
Labels: CCB:FastTrack, IC:2021-03-30

#1236 Fix #1186, Remove useless assignments/checks
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_generic_pool.c
  modules/es/fsw/src/cfe_es_mempool.c
  modules/evs/fsw/src/cfe_evs_task.c
Labels: CCB:FastTrack, IC:2021-03-30

#1256 Fix #1194, check for NULL in SlotUsed helpers
  modules/es/fsw/src/cfe_es_cds.c
  modules/es/fsw/src/cfe_es_mempool.c
  modules/es/fsw/src/cfe_es_resource.c
  modules/sb/fsw/src/cfe_sb_priv.c
Labels: IC:2021-03-30

#1263 Fix #1261, Remove redundant checks in CFE_EVS_EarlyInit
  modules/evs/fsw/src/cfe_evs_task.c
Labels: CCB:FastTrack, IC:2021-03-30

#1242 Fix #1223, #1264 shorten TestRunner function name and update cfe_es_startup.scr docs
  docs/README_functionaltest.md
  modules/cfe_testrunner/inc/cfe_testrunner.h
  modules/cfe_testrunner/src/cfe_testrunner_main.c
Labels: IC:2021-03-30

#1229 Fix #1164, use FS file name parser for commands
  modules/es/fsw/src/cfe_es_perf.c
  modules/es/fsw/src/cfe_es_task.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/fsw/src/cfe_evs_log.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/ut-coverage/evs_UT.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/sb/ut-coverage/sb_UT.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/ut-coverage/tbl_UT.c
Labels: IC:2021-03-30

#1257 Fix #1155, clean up zero copy API
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/fsw/inc/cfe_sb_api_typedefs.h
  modules/core_api/ut-stubs/src/ut_sb_stubs.c
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_priv.h
  modules/sb/ut-coverage/sb_UT.c
  modules/sb/ut-coverage/sb_UT.h
Labels: IC:2021-03-30, breaking, conflicts

#1254 Fix #1181, global variable cleanup
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_backgroundtask.c
  modules/es/fsw/src/cfe_es_erlog.c
  modules/es/fsw/src/cfe_es_global.h
  modules/es/fsw/src/cfe_es_perf.c
  modules/es/fsw/src/cfe_es_start.c
  modules/es/fsw/src/cfe_es_syslog.c
  modules/es/fsw/src/cfe_es_task.c
  modules/es/fsw/src/cfe_es_task.h
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Ready, IC:2021-03-30

#1255 Fix #1206, report PSP version in ES HK TLM
  docs/src/mnem_maps/cfe_es_tlm_mnem_map
  modules/es/eds/cfe_es.xml
  modules/es/fsw/inc/cfe_es_msg.h
  modules/es/fsw/src/cfe_es_task.c
Labels: CCB:Ready, conflicts

#1271 Fix #1270, limit check in pool validation
  modules/es/fsw/src/cfe_es_generic_pool.c
Labels: CCB:FastTrack, CCB:Ready, IC:2021-03-30

#1268 Fix #1267, #1269 add null pointer check
  modules/core_api/fsw/inc/cfe_error.h
  modules/core_api/fsw/inc/cfe_es.h
  modules/es/fsw/src/cfe_es_api.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/fsw/src/cfe_evs.c
  modules/evs/ut-coverage/evs_UT.c
  modules/resourceid/fsw/src/cfe_resourceid_api.c
  modules/resourceid/ut-coverage/test_cfe_resourceid.c
Labels: CCB:FastTrack, CCB:Ready, IC:2021-03-30

#1260 Fix #1259, Add branch coverage option to genhtml
  cmake/Makefile.sample
Labels: CCB:FastTrack, IC:2021-03-30
