Repository nasa/cFE, pull requests merged in 2021-02, with the labels that each got.

#1146 Fix #1145, Update workflow action badge
  README.md
Labels: CCB:FastTrack, docs

#1113 Fix #1014, Remove Test_SB_Cmds_SubRptUnexpCmdCode
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
Labels: CCB:2021-01-27, CCB:FastTrack, IC:2021-02-02

#1115 Fix #1071, Initialize Status in CFE_ES_WaitForSystemState
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB:2021-01-27, CCB:FastTrack, IC:2021-02-02

#1120 Fix #986, Remove unnecessary CFE_MSG_Init in TBL
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/unit-test/tbl_UT.c
Labels: CCB:2021-01-27, CCB:FastTrack, IC:2021-02-02

#1114 Fix #1110, Remove unimplemented ES prototypes
  fsw/cfe-core/src/es/cfe_es_apps.h
Labels: CCB:2021-01-27, CCB:FastTrack, IC:2021-02-02

#1139 Fix #1070 for main branch (merge of 6.8.x after bookkeeping)
  cmake/arch_build.cmake
Labels: CCB:FastTrack

#1147 Fix #1144, Add workflow action timeout
  .github/workflows/static-analysis.yml
Labels: CCB:FastTrack

#1142 Fix #1141, pipe name unset
  fsw/cfe-core/src/sb/cfe_sb_api.c
Labels: CCB:FastTrack, CCB:Ready, IC:2021-02-02

#1101 Fix #1100, Update highest MsgId documentation/verification
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/sb/cfe_sb_verify.h
Labels: CCB:2021-01-27, CCB:FastTrack, Priority: Mission

#1083 Fix #793, Clarify restart/reload app behavior
  docs/src/cfe_es.dox
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_es_msg.h
Labels: CCB:2021-01-13, CCB:2021-01-27, IC:2021-02-02, docs

#1128 Fix #915, Check for file existence in CFE_ES_RestartApp
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB:2021-01-27, IC:2021-02-02

#1116 Fix #1069, Resolve mismatched types in SBR throttle
  modules/sbr/src/cfe_sbr_route_unsorted.c
Labels: CCB:2021-01-27, IC:2021-02-02

#1111 Fix #996, Remove CFE_PLATFORM_SB_MAX_PIPE_DEPTH in favor of OS_QUEUE_MAX_DEPTH
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/inc/cfe_sb_events.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/sb/cfe_sb_verify.h
  fsw/cfe-core/unit-test/sb_UT.c
Labels: CCB:2021-01-27, IC:2021-02-02

#1133 Fix #723, CFE_EVS_Register const correct and report truncation
  fsw/cfe-core/src/evs/cfe_evs.c
  fsw/cfe-core/src/inc/cfe_evs.h
  fsw/cfe-core/ut-stubs/ut_evs_stubs.c
Labels: CCB:2021-01-27, IC:2021-02-02

#1129 Fix #609, Remove CFE_PLATFORM_EVS_LOG_ON undefined option to diasble log
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/inc/cfe_evs_events.h
  fsw/cfe-core/src/inc/private/cfe_es_resetdata_typedef.h
Labels: CCB:2021-01-27, IC:2021-02-02

#1132 Fix #680, Remove table service exclusion logic
  docs/src/cfe_tbl.dox
  fsw/cfe-core/src/es/cfe_es_objtab.c
Labels: CCB:2021-01-27, IC:2021-02-02

#1126 Fix #1122, ES and EVS use default message limits
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/evs/cfe_evs_task.c
  fsw/cfe-core/src/evs/cfe_evs_task.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/evs_UT.c
Labels: CCB:2021-01-27, IC:2021-02-02

#1125 Fix #1123, Convert global CFE_SB_Default_Qos to macro
  docs/src/cfe_sb.dox
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB:2021-01-27, IC:2021-02-02, dependency, deprecate, removed

#1163 Fix #1162, Add CodeQL analysis to workflow
  .github/workflows/codeql-build.yml
Labels: CCB:FastTrack, continuous-integration

#1167 Fix #1166, Remove deployment guide reference
  cmake/README.md
  cmake/sample_defs/cpu1_platform_cfg.h
  docs/cFE Application Developers Guide.md
  docs/src/cfe_es.dox
Labels: CCB:FastTrack, docs

#1148 Fix #139, Do file writes in background
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_erlog.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/fs/cfe_fs_priv.h
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.h
  fsw/cfe-core/src/tbl/cfe_tbl_task.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/fs_UT.h
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
Labels: CCB:2021-02-02, IC:2021-02-23

#1151 Fix #978, put task parameters into task record
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_objtab.c
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_start.h
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB:2021-02-02, IC:2021-02-23

#1158 Fix #790, allow directories and symlinks in FILELIST.
  cmake/arch_build.cmake
Labels: CCB:2021-02-17, IC:2021-02-23

#1168 Fix #735, add comment if null terminated or not.
  cmake/sample_defs/sample_mission_cfg.h
Labels: CCB:2021-02-17, IC:2021-02-23

#1173 Fix #1172, Update to use Ut_Stub_CheckDefaultReturnValue API
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
Labels: CCB:2021-02-24, CCB:FastTrack, IC:2021-02-23, dependency

#1175 Fix #1160, Shorten task info default filename
  cmake/sample_defs/cpu1_platform_cfg.h
Labels: CCB:2021-02-24, CCB:FastTrack, IC:2021-02-23

#1171 cFE Integration candidate: 2021-02-23
  README.md
  cmake/arch_build.cmake
  cmake/sample_defs/cpu1_platform_cfg.h
  cmake/sample_defs/sample_mission_cfg.h
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_apps.h
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/es/cfe_es_erlog.c
  fsw/cfe-core/src/es/cfe_es_objtab.c
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_start.h
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/fs/cfe_fs_api.c
  fsw/cfe-core/src/fs/cfe_fs_priv.h
  fsw/cfe-core/src/inc/cfe_error.h
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_fs.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.h
  fsw/cfe-core/src/tbl/cfe_tbl_task.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/fs_UT.h
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_fs_stubs.c
  fsw/cfe-core/ut-stubs/ut_tbl_stubs.c
Labels: IC:2021-02-23
