Repository nasa/cFE, pull requests merged in 2021-06, with the labels that each got.

#1557 Fix #1548, Include verify headers to validate config
  modules/es/fsw/src/cfe_es_task.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/tbl/fsw/src/cfe_tbl_task.c
  modules/time/fsw/src/cfe_time_task.c
Labels: CCB:Approved, IC:2021-06-01

#1513 Fix #1512, Add Coding Standard Rules in CodeQL
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, continuous-integration

#1591 Fix #1585, Fix Calculate CRC header return description.
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:Approved, CCB:FastTrack, IC:2021-06-01

#1572 Fix #1435, Consistent use of uint16 for EventID
  modules/core_api/fsw/inc/cfe_evs.h
  modules/core_api/ut-stubs/src/cfe_evs_stubs.c
  modules/evs/fsw/src/cfe_evs.c
  modules/evs/fsw/src/cfe_evs_task.h
  modules/evs/fsw/src/cfe_evs_utils.c
  modules/evs/fsw/src/cfe_evs_utils.h
  modules/evs/ut-coverage/evs_UT.c
Labels: CCB:Approved, IC:2021-06-01, conflicts

#1577 Fix #1386, Remove CFE_EVS_Unregister API
  docs/cFE Application Developers Guide.md
  docs/cFE_FunctionalRequirements.csv
  docs/src/cfe_api.dox
  modules/core_api/fsw/inc/cfe_evs.h
  modules/core_api/ut-stubs/src/cfe_evs_stubs.c
  modules/evs/fsw/src/cfe_evs.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/ut-coverage/evs_UT.c
Labels: CCB:Approved, IC:2021-06-01, conflicts

#1584 cFE Integration candidate: 2021-06-01
  .github/workflows/codeql-build.yml
  CMakeLists.txt
  README.md
  cmake/Makefile.sample
  cmake/cfe-common.doxyfile.in
  cmake/mission_build.cmake
  cmake/osal-common.doxyfile.in
  cmake/osalguide.doxyfile.in
  docs/cFE Application Developers Guide.md
  docs/cFE_FunctionalRequirements.csv
  docs/src/cfe_api.dox
  docs/src/osal_fs.dox
  docs/src/osal_timer.dox
  docs/src/osalmain.dox
  modules/core_api/fsw/inc/cfe_error.h
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_evs.h
  modules/core_api/fsw/inc/cfe_evs_api_typedefs.h
  modules/core_api/fsw/inc/cfe_fs.h
  modules/core_api/fsw/inc/cfe_fs_extern_typedefs.h
  modules/core_api/fsw/inc/cfe_msg_api_typedefs.h
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/fsw/inc/cfe_sb_api_typedefs.h
  modules/core_api/fsw/inc/cfe_tbl.h
  modules/core_api/fsw/inc/cfe_time.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/core_api/ut-stubs/src/cfe_evs_stubs.c
  modules/core_private/fsw/inc/cfe_evs_log_typedef.h
  modules/core_private/fsw/inc/cfe_sb_destination_typedef.h
  modules/core_private/fsw/inc/cfe_sbr.h
  modules/es/fsw/src/cfe_es_task.c
  modules/es/fsw/src/cfe_es_verify.h
  modules/es/ut-coverage/es_UT.c
  modules/evs/fsw/inc/cfe_evs_events.h
  modules/evs/fsw/inc/cfe_evs_msg.h
  modules/evs/fsw/src/cfe_evs.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/fsw/src/cfe_evs_task.h
  modules/evs/fsw/src/cfe_evs_utils.c
  modules/evs/fsw/src/cfe_evs_utils.h
  modules/evs/ut-coverage/evs_UT.c
  modules/fs/fsw/src/cfe_fs_api.c
  modules/msg/option_inc/default_cfe_msg_hdr_pri.h
  modules/msg/option_inc/default_cfe_msg_hdr_priext.h
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/sbr/CMakeLists.txt
  modules/sbr/fsw/src/cfe_sbr_route_unsorted.c
  modules/tbl/fsw/src/cfe_tbl_api.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_internal.h
  modules/tbl/fsw/src/cfe_tbl_task.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.h
  modules/tbl/fsw/src/cfe_tbl_verify.h
  modules/time/fsw/src/cfe_time_task.c
  modules/time/fsw/src/cfe_time_tone.c
Labels: IC:2021-06-01

#1555 Fix #1554, add doxygen aliases for OSAL parameter/retvals
  cmake/cfe-common.doxyfile.in
Labels: IC:2021-06-01, docs

#1590 Fix #1483, Add CI workflow to run cFE coverage tests
  .github/workflows/code-coverage.yml
Labels: CCB:Approved, continuous-integration

#1598 Fix #1299, Updated FS Read/WriteHeader API return documentation
  modules/core_api/fsw/inc/cfe_fs.h
Labels: CCB:Approved, CCB:FastTrack

#1601 Fix #567, Document CFE_ES_RunLoop increment task counter behavior
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:Approved, CCB:FastTrack, docs

#1615 Fix #1614, standardize on "docs" subdirectory
  cmake/Makefile.sample
  cmake/arch_build.cmake
  cmake/cfe-common.doxyfile.in
  cmake/cfe-usersguide.doxyfile.in
  cmake/mission-detaildesign.doxyfile.in
  cmake/mission_build.cmake
Labels: CCB:FastTrack

#1603 Fix #1177, Update version description per current design
  docs/src/cfs_versions.dox
Labels: CCB:Approved, CCB:FastTrack, docs

#1602 Fix #741, Document CFE_TBL_Unregister use-case
  modules/core_api/fsw/inc/cfe_tbl.h
Labels: CCB:Approved, CCB:FastTrack, docs

#1596 Fix #1595, provide CFE assert lock/unlock
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_assert/src/cfe_assert_runner.c
Labels: CCB:Approved

#1566 Fix #1442, Simplify CFE_FS_SetTimestamp and fix syslog typo
  modules/cfe_testcase/src/fs_header_test.c
  modules/fs/fsw/src/cfe_fs_api.c
  modules/fs/ut-coverage/fs_UT.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
Labels: CCB:Approved

#1592 Fix #1308, Removed redundant check/set of CFE_CPU_ID_VALUE
  cmake/target/src/target_config.c
Labels: CCB:Approved

#1593 Fix #1544, add time get reference error bit
  modules/time/fsw/inc/cfe_time_msg.h
  modules/time/fsw/src/cfe_time_api.c
  modules/time/fsw/src/cfe_time_utils.c
  modules/time/fsw/src/cfe_time_utils.h
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#1600 Fix #1199, Add workflow to build cFE documentation
  .github/workflows/build-documentation.yml
Labels: CCB:Approved, continuous-integration

#1609 Fix #1205 #1131 #1127 #1029 #942 - Requirements updates
  docs/cFE_FunctionalRequirements.csv
Labels: CCB:Approved

#1610 Fix #1306, ES/ResourceID documentation cleanup
  cmake/global_functions.cmake
  cmake/sample_defs/targets.cmake
  cmake/target/src/target_config.c
  modules/core_api/fsw/inc/cfe_es.h
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_erlog.c
  modules/es/fsw/src/cfe_es_objtab.c
  modules/es/fsw/src/cfe_es_start.c
Labels: CCB:Approved

#1613 Fix #1490, allow multiple sources in add_cfe_coverage_test
  cmake/arch_build.cmake
Labels: CCB:Approved

#1586 Fix #814, add ES Misc Functional test
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_misc_test.c
Labels: CCB:Approved

#1607 Fix #811, add Mempool functional tests
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_mempool_test.c
Labels: CCB:Approved

#1605 Fix #1604, Clean/simplify version header and reporting
  modules/core_api/fsw/inc/cfe_version.h
  modules/es/fsw/src/cfe_es_task.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/tbl/fsw/src/cfe_tbl_task.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/time/fsw/src/cfe_time_task.c
Labels: CCB:Approved

#1612 Fix #1378, 1589, doxygen cleanup
  cmake/arch_build.cmake
  cmake/cfe-common.doxyfile.in
  cmake/cfe-usersguide.doxyfile.in
  cmake/mission-detaildesign.doxyfile.in
  cmake/mission_build.cmake
Labels: CCB:Approved, conflicts

#1611 Fix #1325, Prepend system log messages with function name
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/core_private/ut-stubs/src/ut_osprintf_stubs.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_backgroundtask.c
  modules/es/fsw/src/cfe_es_cds.c
  modules/es/fsw/src/cfe_es_cds_mempool.c
  modules/es/fsw/src/cfe_es_erlog.c
  modules/es/fsw/src/cfe_es_generic_pool.c
  modules/es/fsw/src/cfe_es_mempool.c
  modules/es/fsw/src/cfe_es_perf.c
  modules/es/fsw/src/cfe_es_start.c
  modules/es/fsw/src/cfe_es_task.c
  modules/evs/fsw/src/cfe_evs.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/fsw/src/cfe_evs_utils.c
  modules/evs/ut-coverage/evs_UT.c
  modules/fs/fsw/src/cfe_fs_api.c
  modules/fs/fsw/src/cfe_fs_priv.c
  modules/fs/ut-coverage/fs_UT.c
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_init.c
  modules/sb/fsw/src/cfe_sb_priv.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/sb/fsw/src/cfe_sb_util.c
  modules/tbl/fsw/src/cfe_tbl_api.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_task.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/time/fsw/src/cfe_time_api.c
  modules/time/fsw/src/cfe_time_task.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#1608 Fix #1367, Add cfe functional tests to CI
  .github/workflows/functional-tests.yml
Labels: CCB:Approved, continuous-integration

#1621 Fix #1477, add additional test cases for Child Tasks
  modules/cfe_testcase/src/es_task_test.c
Labels: CCB:Approved

#1630 Fix #1629, correct path to users guide warning log
  .github/workflows/build-documentation.yml
Labels: CCB:FastTrack

#1627 Fix #1626, rename/clean CFE coverage assert macros
  modules/core_private/ut-stubs/inc/ut_support.h
  modules/core_private/ut-stubs/src/ut_support.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/ut-coverage/evs_UT.c
  modules/msg/ut-coverage/test_cfe_msg_ccsdsext.c
  modules/msg/ut-coverage/test_cfe_msg_ccsdspri.c
  modules/msg/ut-coverage/test_cfe_msg_checksum.c
  modules/msg/ut-coverage/test_cfe_msg_fc.c
  modules/msg/ut-coverage/test_cfe_msg_init.c
  modules/msg/ut-coverage/test_cfe_msg_msgid_shared.c
  modules/msg/ut-coverage/test_cfe_msg_msgid_v1.c
  modules/msg/ut-coverage/test_cfe_msg_msgid_v2.c
  modules/msg/ut-coverage/test_cfe_msg_time.c
  modules/sb/ut-coverage/sb_UT.c
  modules/sbr/ut-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/ut-coverage/test_cfe_sbr_map_hash.c
  modules/sbr/ut-coverage/test_cfe_sbr_route_unsorted.c
  modules/tbl/ut-coverage/tbl_UT.c
Labels: CCB:FastTrack

#1623 Fix #465, Added UT tests for cFE ES Api
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1634 Fix #1478, Expand CDS Functional Tests.
  modules/cfe_testcase/src/es_cds_test.c
Labels: CCB:Ready

#1594 Fix #1320 #1583 #508, Event ID updates
  cmake/cfe-common.doxyfile.in
  modules/es/fsw/inc/cfe_es_events.h
  modules/evs/fsw/inc/cfe_evs_events.h
  modules/sb/fsw/inc/cfe_sb_events.h
  modules/tbl/fsw/inc/cfe_tbl_events.h
  modules/time/fsw/inc/cfe_time_events.h
Labels: CCB:Approved, CCB:Ready

#1633 Fix #1625, add test log file
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_assert/src/cfe_assert_priv.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
Labels: CCB:Ready

#1624 Fix #596, scrub all UT_Report calls
  modules/core_private/ut-stubs/inc/ut_support.h
  modules/core_private/ut-stubs/src/ut_support.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/ut-coverage/evs_UT.c
  modules/fs/ut-coverage/fs_UT.c
  modules/fs/ut-coverage/fs_UT.h
  modules/msg/ut-coverage/test_cfe_msg_ccsdsext.c
  modules/msg/ut-coverage/test_cfe_msg_ccsdspri.c
  modules/msg/ut-coverage/test_cfe_msg_checksum.c
  modules/msg/ut-coverage/test_cfe_msg_fc.c
  modules/msg/ut-coverage/test_cfe_msg_init.c
  modules/msg/ut-coverage/test_cfe_msg_msgid_shared.c
  modules/msg/ut-coverage/test_cfe_msg_msgid_v1.c
  modules/msg/ut-coverage/test_cfe_msg_msgid_v2.c
  modules/msg/ut-coverage/test_cfe_msg_time.c
  modules/sb/ut-coverage/sb_UT.c
  modules/sbr/ut-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/ut-coverage/test_cfe_sbr_map_hash.c
  modules/sbr/ut-coverage/test_cfe_sbr_route_unsorted.c
  modules/tbl/ut-coverage/tbl_UT.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved, conflicts

#1444 Fix #1184, Change index type to resolve infinite loop warning
  modules/core_private/ut-stubs/src/ut_support.c
Labels: CCB:Approved, community

#1653 Fix #468, Adding coverage for cfe_es_task.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1638 Fix #1480, Expand FS Header Functional tests.
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_header_test.c
Labels: CCB:Approved
