Repository nasa/cFE, pull requests merged in 2021-12, with the labels that each got.

#1663 Fix #1546, use cfe time clock state enum t in cmd/tlm and handling
  modules/time/fsw/inc/cfe_time_msg.h
  modules/time/fsw/src/cfe_time_utils.c
  modules/time/fsw/src/cfe_time_utils.h
Labels: CCB:Approved

#1873 Fix #1672, return type conversions in CFE_ES_GetTaskName
  modules/cfe_testcase/src/es_task_test.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1909 Fix #1302, Use macro in CFE_ResourceId_IsDefined
  modules/core_api/fsw/inc/cfe_resourceid.h
Labels: CCB:Approved, community

#1911 Fix #1300, CFE_ES_MemAddOff structure to associated CFE_ES_MemAddress_t and CFE_ES_MemOffset_t
  docs/src/mnem_maps/cfe_es_tlm_mnem_map
  modules/cfe_testcase/src/es_info_test.c
  modules/core_api/fsw/inc/cfe_es_extern_typedefs.h
  modules/es/eds/cfe_es.xml
  modules/es/fsw/src/cfe_es_apps.c
Labels: CCB:Approved

#1954 Fix #1952, patch for recursive event loop
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_priv.h
  modules/sb/ut-coverage/sb_UT.c
Labels: CCB:Approved

#1966 Fix #1965, better message type pointer conversion
  modules/cfe_testcase/src/msg_api_test.c
  modules/cfe_testcase/src/sb_sendrecv_test.c
  modules/es/fsw/inc/cfe_es_msg.h
  modules/es/fsw/src/cfe_es_task.c
  modules/es/fsw/src/cfe_es_task.h
  modules/es/ut-coverage/es_UT.c
  modules/evs/fsw/inc/cfe_evs_msg.h
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/fsw/src/cfe_evs_utils.c
  modules/evs/ut-coverage/evs_UT.c
  modules/msg/option_inc/default_cfe_msg_hdr_pri.h
  modules/msg/option_inc/default_cfe_msg_hdr_priext.h
  modules/msg/ut-coverage/test_cfe_msg_checksum.c
  modules/msg/ut-coverage/test_cfe_msg_fc.c
  modules/msg/ut-coverage/test_cfe_msg_init.c
  modules/msg/ut-coverage/test_cfe_msg_time.c
  modules/sb/fsw/inc/cfe_sb_msg.h
  modules/sb/fsw/src/cfe_sb_init.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/sb/fsw/src/cfe_sb_util.c
  modules/sb/ut-coverage/sb_UT.c
  modules/sb/ut-coverage/sb_UT.h
  modules/tbl/fsw/inc/cfe_tbl_msg.h
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_task.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/ut-coverage/tbl_UT.c
  modules/time/fsw/inc/cfe_time_msg.h
  modules/time/fsw/src/cfe_time_task.c
  modules/time/fsw/src/cfe_time_tone.c
  modules/time/fsw/src/cfe_time_utils.c
Labels: CCB:Approved

#1973 Fix #1818, EVS functional test add for different event types
  modules/cfe_testcase/src/evs_send_test.c
Labels: CCB:Approved, community

#1974 Fix #1945, add CFE_SB_ValueToMsgId/MsgIdToValue wrappers
  modules/cfe_testcase/src/message_id_test.c
  modules/cfe_testcase/src/msg_api_test.c
  modules/cfe_testcase/src/sb_subscription_test.c
  modules/cfe_testcase/src/tbl_information_test.c
  modules/cfe_testcase/src/tbl_registration_test.c
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/fsw/inc/cfe_sb_api_typedefs.h
  modules/msg/ut-coverage/test_cfe_msg_msgid_v1.c
Labels: CCB:Approved

#1975 Fix #245, #1944, Message ID type improvements
  modules/cfe_testcase/src/message_id_test.c
  modules/cfe_testcase/src/msg_api_test.c
  modules/cfe_testcase/src/sb_subscription_test.c
  modules/cfe_testcase/src/tbl_information_test.c
  modules/cfe_testcase/src/tbl_registration_test.c
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/fsw/inc/cfe_sb_api_typedefs.h
  modules/core_api/fsw/inc/cfe_sb_extern_typedefs.h
  modules/msg/ut-coverage/test_cfe_msg_msgid_shared.c
  modules/msg/ut-coverage/test_cfe_msg_msgid_v1.c
  modules/sb/ut-coverage/sb_UT.c
Labels: CCB:Approved

#1980 Fix #1979, implement abstract config registry module
  cmake/mission_defaults.cmake
  modules/config/CMakeLists.txt
  modules/config/cmake/cfe_config_ids.h.in
  modules/config/cmake/cfe_config_map.c.in
  modules/config/fsw/src/cfe_config_get.c
  modules/config/fsw/src/cfe_config_init.c
  modules/config/fsw/src/cfe_config_lookup.c
  modules/config/fsw/src/cfe_config_map.h
  modules/config/fsw/src/cfe_config_priv.h
  modules/config/fsw/src/cfe_config_set.c
  modules/config/fsw/src/cfe_config_table.h
  modules/config/mission_build.cmake
  modules/config/ut-coverage/CMakeLists.txt
  modules/config/ut-coverage/test_cfe_config.c
  modules/core_api/fsw/inc/cfe_config.h
  modules/core_api/fsw/inc/cfe_config_api_typedefs.h
  modules/core_api/ut-stubs/CMakeLists.txt
  modules/core_api/ut-stubs/src/cfe_config_handlers.c
  modules/core_api/ut-stubs/src/cfe_config_stubs.c
  modules/core_private/fsw/inc/cfe_config_core_internal.h
  modules/core_private/ut-stubs/CMakeLists.txt
  modules/core_private/ut-stubs/src/cfe_config_core_internal_stubs.c
  modules/es/fsw/src/cfe_es_objtab.c
  modules/es/fsw/src/cfe_es_task.c
  modules/resourceid/fsw/inc/cfe_core_resourceid_basevalues.h
Labels: enhancement, CCB:Approved

#1986 Fix #1984, avoid aliasing warnings
  modules/cfe_testcase/src/tbl_content_mang_test.c
  modules/core_api/ut-stubs/src/cfe_es_handlers.c
  modules/core_api/ut-stubs/src/cfe_fs_handlers.c
  modules/core_api/ut-stubs/src/cfe_sb_handlers.c
  modules/core_private/ut-stubs/src/ut_support.c
  modules/es/ut-coverage/es_UT.c
  modules/sb/ut-coverage/sb_UT.c
  modules/tbl/ut-coverage/tbl_UT.c
Labels: CCB:Approved

#1995 Fix #1988, consolidate repeated MSG stub setup in sb_UT
  modules/core_private/ut-stubs/inc/ut_support.h
  modules/core_private/ut-stubs/src/ut_support.c
  modules/sb/ut-coverage/sb_UT.c
Labels: CCB:Approved

#1999 Fix #1928, checking against IsNewOffset only
  modules/es/fsw/src/cfe_es_cds.c
Labels: CCB:Approved, community

#2002 Fix #1537, replacing hardcoded message limit in TIME services
  modules/time/fsw/src/cfe_time_task.c
Labels: CCB:Approved, community
