Repository nasa/cFE, pull requests merged in 2021-08, with the labels that each got.

#1739 Fix #1738 Add cast to MIR prints
  modules/time/ut-coverage/time_UT.c
Labels: CCB:FastTrack, CCB:Ready

#1752 Fix #1751, Add null pointer check to table GetAddresses and ReleaseAddresses
  modules/tbl/fsw/src/cfe_tbl_api.c
Labels: CCB:Ready

#1731 Fix #1730, Explain FS Header offset & add offset functional tests.
  modules/cfe_testcase/src/fs_header_test.c
  modules/core_api/fsw/inc/cfe_fs.h
Labels: CCB:Ready

#1758 Fix #1757, Handle fail status from internal functions of CFE_MSG_GetT…
  modules/msg/fsw/src/cfe_msg_msgid_shared.c
Labels: CCB:Ready

#1742 Fix #1741, Remove SB get last message sender info requirement
  docs/cFE_FunctionalRequirements.csv
Labels: CCB:Approved

#1732 Fix #1725 Update time_UT.c to use UtAssert_MIR
  modules/cfe_testcase/src/es_misc_test.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved, conflicts

#1736 Fix #1678 Add Functional Tests for cFE Message ID APIs
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/message_id_test.c
Labels: CCB:Ready, unit-test

#1707 Fix #1690, Tests for time conversion api
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/time_conversion_test.c
Labels: CCB:Approved, community

#1759 cFE Integration candidate: 2021-08-03
  README.md
  docs/cFE_FunctionalRequirements.csv
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_misc_test.c
  modules/cfe_testcase/src/evs_send_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/cfe_testcase/src/message_id_test.c
  modules/cfe_testcase/src/time_conversion_test.c
  modules/core_api/fsw/inc/cfe_fs.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/msg/fsw/src/cfe_msg_msgid_shared.c
  modules/tbl/fsw/src/cfe_tbl_api.c
  modules/time/ut-coverage/time_UT.c
Labels: community

#1737 Fix #1733, Move global count into test global struct.
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_util_test.c
Labels: CCB:Approved

#1722 Fix #806, Add application control functional tests
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_application_control_test.c
Labels: CCB:Ready, unit-test

#1734 Add table api functional tests
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/inc/cfe_test_tbl.h
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/cfe_test_table.c
  modules/cfe_testcase/src/cfe_test_table.h
  modules/cfe_testcase/src/tbl_content_access_test.c
  modules/cfe_testcase/src/tbl_content_mang_test.c
  modules/cfe_testcase/src/tbl_information_test.c
  modules/cfe_testcase/src/tbl_registration_test.c
  modules/cfe_testcase/tables/cfe_test_tbl.c
Labels: CCB:Approved

#1753 Fix #813, Add Generic Counter API test
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_counter_test.c
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:Approved

#1716 Fix #1645, Add resource ID API functional tests
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_resource_id_test.c
Labels: CCB:Ready

#1766 Fix #1644, finish ES misc API functional test
  modules/cfe_testcase/src/es_misc_test.c
Labels: CCB:Ready

#1764 Fix #1763, last char truncated in coverage log output
  modules/core_private/ut-stubs/src/ut_support.c
Labels: CCB:Ready

#1728 Fix #1727, mistakes in some copyright headers
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_priv.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_mempool_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/cfe_testcase/src/sb_pipe_mang_test.c
  modules/cfe_testcase/src/time_current_test.c
  modules/core_private/ut-stubs/src/cfe_es_core_internal_handlers.c
  modules/core_private/ut-stubs/src/cfe_fs_core_internal_handlers.c
  modules/resourceid/fsw/src/cfe_resourceid_api.c
Labels: CCB:Ready, docs

#1767 Fix #1692, Add misc time api functional test
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/time_misc_test.c
Labels: CCB:Ready

#1749 Fix #1649, Add Functional Test for EVS Reset Filters API.
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/evs_filters_test.c
Labels: CCB:Approved

#1796 Fix #1774, replace VOIDCALL assert macro
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/fs_header_test.c
Labels: CCB:Ready

#1790 Fix #1784, add CFE assert macros to functional test
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_counter_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/cfe_testcase/src/sb_pipe_mang_test.c
Labels: CCB:Approved

#1779 Fix #1775, #1773 - Adds invalid id syslog to for CFE_ES_DeleteApp and CFE_ES_ReloadApp and verifies required reporting
  modules/core_private/ut-stubs/inc/ut_osprintf_stubs.h
  modules/core_private/ut-stubs/src/ut_osprintf_stubs.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1785 Fixes #1776, #1770, Stop memory leak & add cds size test.
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_mempool_test.c
Labels: CCB:Approved

#1765 Fix #1726, mark read only inputs as const
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/ut-stubs/src/cfe_es_stubs.c
  modules/core_api/ut-stubs/src/cfe_sb_stubs.c
  modules/es/fsw/src/cfe_es_api.c
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_priv.h
Labels: CCB:Approved

#1804 Fix #1760, check resource ID idx is less than max
  modules/cfe_testcase/src/es_resource_id_test.c
Labels: CCB:Approved

#1778 Fix #807, Add ES Application Behavior Functional Tests
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_behavior_test.c
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:Approved

#1801 Fix #1762, Update CFE_ES_RunLoop documentation
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:Approved, docs

#1745 Fix #1677, Add Message API Functional Test
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/msg_api_test.c
Labels: unit-test, conflicts, community

#1798 Partial #1724, update in/out status and nonnull/nonzero tags
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_evs.h
  modules/core_api/fsw/inc/cfe_fs.h
  modules/core_api/fsw/inc/cfe_msg.h
  modules/core_api/fsw/inc/cfe_resourceid.h
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/fsw/inc/cfe_tbl.h
  modules/core_api/fsw/inc/cfe_time.h
Labels: CCB:Approved

#1800 Fix #812 Add Perf API functional tests
  .github/workflows/functional-tests.yml
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_perf_test.c
Labels: CCB:Approved

#1808 cFE Integration candidate 2021-08-17
  .github/workflows/functional-tests.yml
  README.md
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_behavior_test.c
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_counter_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_mempool_test.c
  modules/cfe_testcase/src/es_perf_test.c
  modules/cfe_testcase/src/es_resource_id_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/cfe_testcase/src/msg_api_test.c
  modules/cfe_testcase/src/sb_pipe_mang_test.c
  modules/cfe_testcase/src/time_external_test.c
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_evs.h
  modules/core_api/fsw/inc/cfe_fs.h
  modules/core_api/fsw/inc/cfe_msg.h
  modules/core_api/fsw/inc/cfe_resourceid.h
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/fsw/inc/cfe_tbl.h
  modules/core_api/fsw/inc/cfe_time.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/core_api/ut-stubs/src/cfe_es_stubs.c
  modules/core_api/ut-stubs/src/cfe_sb_stubs.c
  modules/core_private/ut-stubs/inc/ut_osprintf_stubs.h
  modules/core_private/ut-stubs/src/ut_osprintf_stubs.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/ut-coverage/es_UT.c
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_priv.h
Labels: community

#1803 Fix #1680 #1681 #1682, add software bus tests
  cmake/sample_defs/cpu1_msgids.h
  cmake/sample_defs/sample_mission_cfg.h
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/sb_sendrecv_test.c
  modules/cfe_testcase/src/sb_subscription_test.c
Labels: CCB:Approved

#1756 Fix #1755, separate variable for OSAL status
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_io.c
  modules/core_private/ut-stubs/src/ut_osprintf_stubs.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_backgroundtask.c
  modules/es/fsw/src/cfe_es_cds.c
  modules/es/fsw/src/cfe_es_cds_mempool.c
  modules/es/fsw/src/cfe_es_erlog.c
  modules/es/fsw/src/cfe_es_mempool.c
  modules/es/fsw/src/cfe_es_perf.c
  modules/es/fsw/src/cfe_es_start.c
  modules/es/fsw/src/cfe_es_syslog.c
  modules/es/fsw/src/cfe_es_task.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/fsw/src/cfe_evs_log.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/ut-coverage/evs_UT.c
  modules/fs/fsw/src/cfe_fs_api.c
  modules/fs/fsw/src/cfe_fs_priv.c
  modules/fs/ut-coverage/fs_UT.c
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_init.c
  modules/sb/fsw/src/cfe_sb_priv.c
  modules/sb/fsw/src/cfe_sb_priv.h
  modules/sb/ut-coverage/sb_UT.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/ut-coverage/tbl_UT.c
  modules/time/fsw/src/cfe_time_task.c
  modules/time/fsw/src/cfe_time_tone.c
  modules/time/fsw/src/cfe_time_utils.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#1809 Fix #1807, increase SB pool max size bucket
  cmake/sample_defs/cpu1_platform_cfg.h
Labels: CCB:Approved

#1842 Fix #1840, Add Null check for CFE_ResourceId_FindNext
  modules/core_api/fsw/inc/cfe_resourceid.h
  modules/resourceid/fsw/src/cfe_resourceid_api.c
  modules/resourceid/ut-coverage/test_cfe_resourceid.c
Labels: CCB:FastTrack

#1828 Improve tbl coverage tests
  modules/tbl/ut-coverage/tbl_UT.c
  modules/tbl/ut-coverage/tbl_UT.h
Labels: CCB:Approved

#1833 Fix #1824, Add missing cases for msg id func tests
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/msg_api_test.c
Labels: CCB:Approved

#1832 Fix #1831, Consolidate msg get/set doxygen group
  docs/src/cfe_api.dox
  modules/core_api/fsw/inc/cfe_sb.h
Labels: CCB:Approved, docs

#1836 Fix #473 Adding coverage tests to cFE TIME
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#1848 Fix #1847, enable strict resource id w/OMIT_DEPRECATED
  cmake/sample_defs/global_build_options.cmake
Labels: CCB:Ready, CCB:FastTrack

#1845 HOTFIX IC-20210819, type correction TBL coverage test
  modules/tbl/ut-coverage/tbl_UT.c
Labels: CCB:Ready

#1806 Fix #1805, Add test for ES BackgroundWakeup
  modules/cfe_testcase/src/es_misc_test.c
Labels: CCB:Approved

#1813 Fix #1786, Success Test for CFE_ES_RestartApp
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1814 Fix #1794, Subscribe to Message Limit Greater Than CFE_PLATFORM_SB_DEFAULT_MSG_LIMIT
  modules/sb/ut-coverage/sb_UT.c
Labels: CCB:Approved

#1811 Fix #1787, Success Test for CFE_ES_GetMemPoolStats
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#1822 Fix #1821, Group MSG APIs documentation by header type
  docs/src/cfe_api.dox
  modules/core_api/fsw/inc/cfe_msg.h
Labels: CCB:Approved, docs

#1816 Fix #1815, add retroactive CFE status asserts
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_assert/src/cfe_assert_priv.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/src/es_cds_test.c
Labels: CCB:Approved

#1854 Fix #1851, remove unused CFE_TBL_ERR_BAD_APP_ID
  modules/core_api/fsw/inc/cfe_error.h
  modules/core_api/fsw/inc/cfe_tbl.h
  modules/tbl/fsw/src/cfe_tbl_api.c
  modules/tbl/fsw/src/cfe_tbl_internal.h
Labels: CCB:Ready

#1855 Fix #1852, correct syslog message in pool create
  modules/es/fsw/src/cfe_es_mempool.c
Labels: CCB:Ready

#1853 Fix #1850, remove unused CFE_ES_POOL_BOUNDS_ERROR
  modules/core_api/fsw/inc/cfe_error.h
  modules/core_api/fsw/inc/cfe_es.h
  modules/es/fsw/src/cfe_es_mempool.c
Labels: CCB:Ready

#1856 Fix #1827 Check error ctr to TransmitMsg test
  modules/sb/ut-coverage/sb_UT.c
Labels: CCB:Ready

#1857 Fix #1771, End Child Task requirement remove error code
  docs/cFE_FunctionalRequirements.csv
Labels: CCB:Ready

#1782 Fix #1679, Add functional tests for resource misc
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/resource_id_misc_test.c
Labels: CCB:Approved

#1870 Fix #1812, Add SB API test cases
  modules/cfe_testcase/src/sb_pipe_mang_test.c
  modules/cfe_testcase/src/sb_sendrecv_test.c
  modules/cfe_testcase/src/sb_subscription_test.c
  modules/core_api/fsw/inc/cfe_sb.h
Labels: CCB:Ready

#1869 Fix #1866, Add ES API test cases
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_counter_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_mempool_test.c
  modules/cfe_testcase/src/es_misc_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:Ready

#1872 Fix #1868, Add TBL API test cases
  modules/cfe_testcase/src/tbl_content_access_test.c
  modules/cfe_testcase/src/tbl_content_mang_test.c
  modules/cfe_testcase/src/tbl_information_test.c
  modules/cfe_testcase/src/tbl_registration_test.c
  modules/cfe_testcase/tables/cfe_test_tbl.c
  modules/core_api/fsw/inc/cfe_tbl.h
Labels: CCB:Ready

#1871 Fix #1867, Add FS API test cases
  modules/cfe_testcase/src/fs_util_test.c
  modules/core_api/fsw/inc/cfe_fs.h
Labels: CCB:Ready

#1902 Fix #1616, Incorrect OSAL Format in Users Guide Reference
  docs/cFE Application Developers Guide.md
Labels: CCB:Ready, docs

#1884 Fix #1880, Improve FS coverage
  modules/fs/ut-coverage/fs_UT.c
Labels: CCB:Approved

#1889 Fix #1888, Improve MSG branch coverage
  modules/msg/ut-coverage/test_cfe_msg_msgid_shared.c
Labels: CCB:Ready

#1891 Fix #1890, Improve resource ID branch coverage
  modules/resourceid/ut-coverage/test_cfe_resourceid.c
Labels: CCB:Ready

#1894 Fix #1893, Improve SBR branch coverage
  modules/sbr/ut-coverage/test_cfe_sbr_route_unsorted.c
Labels: CCB:Ready

#1896 Fix #1895, Improve TIME branch coverage
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Ready

#1904 Fix #1897 #1899, Improve TBL code coverage
  modules/tbl/ut-coverage/tbl_UT.c
Labels: CCB:Ready
