Repository nasa/cFE, pull requests merged in 2021-01, with the labels that each got.

#1056 Fix #1054, Resolve osal guide generation warnings
  docs/src/osalmain.dox
Labels: CCB-FastTrack, IC-20210105

#1060 fix #1059 - corrects documentation for CFE_SB_GetPipeName() stub
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB-FastTrack, IC-20210105, docs

#1066 cFE Integration Candidate: 2021-01-05
  .github/workflows/static-analysis.yml
  README.md
  docs/src/osalmain.dox
  fsw/cfe-core/src/inc/cfe_version.h
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: IC-20210105

#1067 Fix #260, Remove unused network_includes.h
  fsw/cfe-core/src/inc/network_includes.h
Labels: CCB-FastTrack, CCB-READY, IC-20200112

#1063 fix #1062 - remove CFE_SB_TimeOut_t typedef
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
Labels: CCB-20210106, IC-20210112

#1050 Fix #1049, replace OS_fsBlocksFree
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB-20210106, IC-20210112, dependency

#1058 Fix #1051, use OSAL time conversion/access methods
  fsw/cfe-core/src/es/cfe_es_backgroundtask.c
  fsw/cfe-core/src/time/cfe_time_api.c
  fsw/cfe-core/src/time/cfe_time_utils.c
  fsw/cfe-core/unit-test/time_UT.c
  fsw/cfe-core/unit-test/ut_support.c
Labels: CCB-20210106, IC-20210112, dependency

#1082 Fix #1081, Correct deprecation directive typo
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
Labels: CCB-FastTrack, IC-20210112

#1048 Fix #1068, Create cFE Security Policy Markdown
  SECURITY.md
Labels: CCB-20210106, CCB:FastTrack, IC:2021-01-19, docs, security

#1086 Fix #904, Update cpuname targets.cmake documentation
  cmake/sample_defs/targets.cmake
Labels: CCB:FastTrack, IC:2021-01-19

#1091 Fix #1090, UT event check bounds
  fsw/cfe-core/unit-test/tbl_UT.c
  fsw/cfe-core/unit-test/ut_support.c
Labels: CCB:2021-01-13, CCB:FastTrack, IC:2021-01-19

#1076 Fix #449, Add OS_printf to CFE_ES_SYSLOG_APPEND
  fsw/cfe-core/src/es/cfe_es_log.h
Labels: CCB:FastTrack, IC:2021-01-19

#1099 Fix #933, Remove SenderReporting from SB global
  cmake/sample_defs/cpu1_platform_cfg.h
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_verify.h
  fsw/cfe-core/unit-test/sb_UT.c
Labels: CCB:FastTrack, IC:2021-01-19

#1106 Fix #954, Handle debug events in unit test
  fsw/cfe-core/unit-test/evs_UT.c
Labels: CCB:FastTrack, IC:2021-01-19

#1085 Fix #901, Remove UT_CheckForOpenSockets references
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/ut_support.h
Labels: CCB:2021-01-13, IC:2021-01-19

#1053 Fix #1052, Refactor UT_ClearForceFail to UT_ClearDefaultReturnValue
  fsw/cfe-core/unit-test/ut_support.c
Labels: CCB:2021-01-13, dependency

#905 Fix #903, Add CFE_SB_GetUserData padding check
  fsw/cfe-core/unit-test/sb_UT.c
Labels: CCB-20200923, CCB:2021-01-13, dependency, unit-test

#1077 Fix #488, Pad msg headers to 64 bit
  modules/msg/mission_inc/default_cfe_msg_hdr_pri.h
  modules/msg/mission_inc/default_cfe_msg_hdr_priext.h
Labels: CCB:2021-01-13

#1075 Fix #1074, Refactor CFE_TIME_RegisterSynchCallback
  fsw/cfe-core/src/time/cfe_time_api.c
Labels: CCB:2021-01-13, IC:2021-01-19

#1092 Fix #1073, software bus locking
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_cds.c
  fsw/cfe-core/src/es/cfe_es_cds.h
  fsw/cfe-core/src/es/cfe_es_mempool.c
  fsw/cfe-core/src/es/cfe_es_mempool.h
  fsw/cfe-core/src/es/cfe_es_resource.c
  fsw/cfe-core/src/es/cfe_es_resource.h
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/inc/cfe_es.h
  fsw/cfe-core/src/inc/cfe_resourceid.h
  fsw/cfe-core/src/inc/cfe_sb.h
  fsw/cfe-core/src/inc/cfe_sb_msg.h
  fsw/cfe-core/src/inc/private/cfe_resourceid_internal.h
  fsw/cfe-core/src/sb/cfe_sb_api.c
  fsw/cfe-core/src/sb/cfe_sb_buf.c
  fsw/cfe-core/src/sb/cfe_sb_init.c
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/sb/cfe_sb_priv.h
  fsw/cfe-core/src/sb/cfe_sb_task.c
  fsw/cfe-core/src/time/cfe_time_tone.c
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/sb_UT.h
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
  fsw/cfe-core/ut-stubs/ut_sb_stubs.c
Labels: CCB:2021-01-13, IC:2021-01-19

#1107 Fix #955, Remove OS_printf stub count checks in UT
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/ut_osprintf_stubs.c
  fsw/cfe-core/unit-test/ut_osprintf_stubs.h
Labels: CCB:2021-01-21

#1084 Fix #877, Remove duplicate CFE_MISSION_REV define
  cmake/sample_defs/cpu1_platform_cfg.h
Labels: CCB:2021-01-13, IC:2021-01-19

#1104 Fix #945, Finish CFE_PLATFORM_ES_PERF_MAX_IDS removal
  cmake/sample_defs/cpu1_platform_cfg.h
  cmake/sample_defs/sample_perfids.h
  fsw/cfe-core/src/inc/cfe_es_events.h
  fsw/cfe-core/unit-test/es_UT.c
Labels: CCB:2021-01-21

#1098 Fix #932 and #1089, strncpy cleanup and UT updates for mission sizing of API_LEN and PATH_LEN
  fsw/cfe-core/src/es/cfe_es_api.c
  fsw/cfe-core/src/es/cfe_es_apps.c
  fsw/cfe-core/src/es/cfe_es_erlog.c
  fsw/cfe-core/src/es/cfe_es_start.c
  fsw/cfe-core/src/es/cfe_es_task.c
  fsw/cfe-core/src/es/cfe_es_task.h
  fsw/cfe-core/src/sb/cfe_sb_priv.c
  fsw/cfe-core/src/tbl/cfe_tbl_api.c
  fsw/cfe-core/src/tbl/cfe_tbl_internal.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.c
  fsw/cfe-core/src/tbl/cfe_tbl_task.h
  fsw/cfe-core/src/tbl/cfe_tbl_task_cmds.c
  fsw/cfe-core/src/time/cfe_time_task.c
  fsw/cfe-core/src/time/cfe_time_utils.c
  fsw/cfe-core/src/time/cfe_time_utils.h
  fsw/cfe-core/unit-test/es_UT.c
  fsw/cfe-core/unit-test/evs_UT.c
  fsw/cfe-core/unit-test/fs_UT.c
  fsw/cfe-core/unit-test/sb_UT.c
  fsw/cfe-core/unit-test/tbl_UT.c
Labels: CCB:2021-01-21

#1135 Fix #1134, Add UtDebug output to CFE_ES_WriteToSysLog stub
  fsw/cfe-core/ut-stubs/ut_es_stubs.c
Labels: CCB:FastTrack, CCB:Ready, IC:2021-01-19

#1072 Fix #1070, patch PSP include directory reference
  cmake/arch_build.cmake
Labels: CCB:2021-01-13, CCB:FastTrack, IC:2021-02-02, cFS-Bootes

#1112 Fix #997, Simplify UT_InitData SB setup
  fsw/cfe-core/unit-test/ut_support.c
Labels: CCB:2021-01-27, CCB:FastTrack, IC:2021-02-02

#1121 Fix #780, Hex output for return checking ASSERTs
  fsw/cfe-core/unit-test/ut_support.c
Labels: CCB:2021-01-27, CCB:FastTrack, IC:2021-02-02
