Repository nasa/cFE, pull requests merged in 2021-09, with the labels that each got.

#1913 Fix #1912, Update time tests to use bitmask check macros
  modules/cfe_testcase/src/time_current_test.c
Labels: CCB:Ready, dependency

#1923 Fix #1918, remove extra word in comment
  cmake/sample_defs/targets.cmake
Labels: CCB:Ready, docs

#1922 Fix #1905, Improve SB coverage
  modules/sb/ut-coverage/sb_UT.c
  modules/sb/ut-coverage/sb_UT.h
Labels: CCB:Approved

#1903 Fix #1216, Update Directory Diagrams in App Developer Guide
  docs/cFE Application Developers Guide.md
  docs/media/cFE_Application_Developers_Guide_image10.png
  docs/media/cFE_Application_Developers_Guide_image11.png
  docs/media/cFE_Application_Developers_Guide_image5.png
  docs/media/cFE_Application_Developers_Guide_image6.png
  docs/media/cFE_Application_Developers_Guide_image7.png
  docs/media/cFE_Application_Developers_Guide_image8.png
  docs/media/cFE_Application_Developers_Guide_image9.png
Labels: CCB:Approved, docs

#1936 Fix #1878 #1696, Improve ES code coverage
  modules/core_private/ut-stubs/inc/ut_osprintf_stubs.h
  modules/core_private/ut-stubs/src/ut_osprintf_stubs.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Ready

#1938 Fix #1906, Enforce minimum code coverage
  .github/workflows/code-coverage.yml
Labels: CCB:Ready

#1941 Fix #1931 Support unimplemented features in MSG ft
  modules/cfe_testcase/src/msg_api_test.c
  modules/cfe_testcase/src/sb_sendrecv_test.c
Labels: CCB:Ready

#1948 Fix #1835, CFE_Assert macro names
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_counter_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/cfe_testcase/src/resource_id_misc_test.c
  modules/cfe_testcase/src/sb_pipe_mang_test.c
  modules/cfe_testcase/src/sb_sendrecv_test.c
Labels: CCB:Approved

#1950 Fix #1949, update msgid testcase to match implementation
  modules/cfe_testcase/src/message_id_test.c
  modules/core_api/fsw/inc/cfe_msg.h
Labels: CCB:Approved

#1962 Fix #1961, Single time domain in functional time tests
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/time_conversion_test.c
  modules/cfe_testcase/src/time_current_test.c
Labels: CCB:Ready

#1943 Fix #1942, add missing inclusions in CFE API headers
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_tbl_api_typedefs.h
Labels: CCB:Approved

#1964 Fix #1963, Use existing /ram for FS header test
  modules/cfe_testcase/src/fs_header_test.c
Labels: CCB:Ready

#1956 Fix #1955, Add static local to function test so data section is nonzero
  modules/cfe_testcase/src/cfe_test.c
Labels: CCB:Ready, unit-test

#1958 Fix #1957, Functional CRC converted to MIR to handle different implementations
  modules/cfe_testcase/src/es_misc_test.c
Labels: CCB:Ready

#1970 Fix #1969, Confirm sb/time reset requirements in coverage test
  modules/sb/ut-coverage/sb_UT.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Ready

#1947 Fix broken link in App Developers Guide
  docs/cFE Application Developers Guide.md
Labels: CCB:Ready, docs, community

#1967 cFE Integration candidate: 2021-09-21
  README.md
  docs/cFE Application Developers Guide.md
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_counter_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_misc_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/cfe_testcase/src/message_id_test.c
  modules/cfe_testcase/src/resource_id_misc_test.c
  modules/cfe_testcase/src/sb_pipe_mang_test.c
  modules/cfe_testcase/src/sb_sendrecv_test.c
  modules/cfe_testcase/src/time_conversion_test.c
  modules/cfe_testcase/src/time_current_test.c
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_msg.h
  modules/core_api/fsw/inc/cfe_tbl_api_typedefs.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/sb/fsw/src/cfe_sb_buf.c
  modules/sb/ut-coverage/sb_UT.c
  modules/time/ut-coverage/time_UT.c
Labels: community
