Repository nasa/cFE, pull requests merged in 2021-04, with the labels that each got.

#1274 Fix #1273, remove PspConfig global object
  cmake/target/inc/target_config.h
  cmake/target/src/target_config.c
  modules/es/fsw/src/cfe_es_task.c
Labels: IC:2021-04-06

#1279 cFE Integration candidate: 2021-04-02
  README.md
  cmake/target/inc/target_config.h
  cmake/target/src/target_config.c
  modules/core_api/fsw/inc/cfe_version.h
  modules/es/fsw/src/cfe_es_task.c
Labels: IC:2021-04-02

#1251 Fix #808, ES API functional tests
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_test.c
Labels: CCB:Reviewed, IC:2021-04-06

#1290 Fix #1287, split interface and implementation modules
  cmake/arch_build.cmake
  cmake/mission_build.cmake
  cmake/mission_defaults.cmake
  cmake/target/CMakeLists.txt
  modules/core_api/CMakeLists.txt
  modules/core_api/ut-stubs/CMakeLists.txt
  modules/core_private/CMakeLists.txt
  modules/core_private/ut-stubs/CMakeLists.txt
Labels: CCB:2021-04-14, CCB:FastTrack, CCB:Reviewed

#1376 Fix #1337, add docs to CFE_ES_RegisterCDS() regarding clearing
  modules/core_api/fsw/inc/cfe_es.h
Labels: CCB:FastTrack, CCB:Reviewed, CFS-40, IC:2021-04-20

#1292 Fix #1281, remove testrunner and convert testcase to app
  cmake/mission_defaults.cmake
  cmake/sample_defs/cpu1_cfe_es_startup.scr
  docs/README_functionaltest.md
  modules/cfe_assert/CMakeLists.txt
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_assert/src/cfe_assert_priv.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testrunner/CMakeLists.txt
  modules/cfe_testrunner/inc/cfe_testrunner.h
Labels: CCB:2021-04-14, CCB:Approved, CCB:FastTrack

#1406 cFE Integration candidate: 2021-04-20
  README.md
  cmake/arch_build.cmake
  cmake/mission_build.cmake
  cmake/mission_defaults.cmake
  cmake/sample_defs/cpu1_cfe_es_startup.scr
  cmake/target/CMakeLists.txt
  docs/README_functionaltest.md
  modules/cfe_assert/CMakeLists.txt
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_init.c
  modules/cfe_assert/src/cfe_assert_io.c
  modules/cfe_assert/src/cfe_assert_priv.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testrunner/CMakeLists.txt
  modules/cfe_testrunner/inc/cfe_testrunner.h
  modules/core_api/CMakeLists.txt
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/core_api/ut-stubs/CMakeLists.txt
  modules/core_private/CMakeLists.txt
  modules/core_private/ut-stubs/CMakeLists.txt
Labels: IC:2021-04-20

#1379 Fix #1317, memory pool pointer type
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/ut-stubs/src/ut_es_stubs.c
  modules/es/fsw/src/cfe_es_mempool.c
Labels: CCB:Approved, CFS-40

#1289 Fix #809, es child task functional test
  cmake/sample_defs/cpu1_cfe_es_startup.scr
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_task_test.c
Labels: CCB:2021-04-14, CCB:Approved, IC:2021-04-27

#1286 Fix #1285, Remove broken BUILDDIR reference
  cmake/Makefile.sample
Labels: CCB:2021-04-14, CCB:Approved, IC:2021-04-27

#1305 Fix #1301, remove option for "osal_compatible"
  modules/resourceid/CMakeLists.txt
  modules/resourceid/fsw/inc/cfe_resourceid_basevalue.h
  modules/resourceid/mission_build.cmake
Labels: CCB:2021-04-14, CCB:Approved

#1374 Fix #1311, CFE_SUCCESS constant type
  modules/core_api/fsw/inc/cfe_error.h
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1316 Fix #1314, Remove Unused Error Codes
  modules/core_api/fsw/inc/cfe_error.h
Labels: CCB:2021-04-14, IC:2021-04-27

#1370 Fix #1330, better warning about malformed startup line
  modules/core_private/ut-stubs/src/ut_osprintf_stubs.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1373 Fix #1338, check status of call to CFE_ES_CDS_CachePreload
  modules/es/fsw/src/cfe_es_cds.c
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1384 Fix #1340, update documentation for CFE_ES_DeleteCDS
  modules/core_api/fsw/inc/cfe_es_core_internal.h
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1385 Fix #1345, exception logic when app/task is not found
  modules/es/fsw/src/cfe_es_erlog.c
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1372 Fix #1346, error if alignment size not a power of two
  modules/es/fsw/src/cfe_es_generic_pool.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1368 Fix #1349, remove unneeded CFE_ES_SYSLOG_APPEND macro
  modules/es/fsw/src/cfe_es_cds.c
  modules/es/fsw/src/cfe_es_cds_mempool.c
  modules/es/fsw/src/cfe_es_log.h
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1382 Fix #1355, improve documentation for resourceID patterns
  modules/es/fsw/src/cfe_es_cds.h
  modules/es/fsw/src/cfe_es_mempool.h
  modules/es/fsw/src/cfe_es_resource.h
  modules/sb/fsw/src/cfe_sb_priv.h
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1371 Fix #1365, assert CFE_RESOURCEID_MAX is a bitmask
  modules/resourceid/fsw/src/cfe_resourceid_api.c
Labels: CCB:Approved, CFS-40, IC:2021-04-27

#1431 cFE Integration candidate: 2021-04-27
  README.md
  cmake/Makefile.sample
  cmake/sample_defs/cpu1_cfe_es_startup.scr
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/core_api/fsw/inc/cfe_error.h
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_es_core_internal.h
  modules/core_api/fsw/inc/cfe_version.h
  modules/core_api/ut-stubs/src/ut_es_stubs.c
  modules/core_private/ut-stubs/src/ut_osprintf_stubs.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_cds.c
  modules/es/fsw/src/cfe_es_cds.h
  modules/es/fsw/src/cfe_es_cds_mempool.c
  modules/es/fsw/src/cfe_es_erlog.c
  modules/es/fsw/src/cfe_es_generic_pool.c
  modules/es/fsw/src/cfe_es_log.h
  modules/es/fsw/src/cfe_es_mempool.c
  modules/es/fsw/src/cfe_es_mempool.h
  modules/es/fsw/src/cfe_es_resource.h
  modules/es/ut-coverage/es_UT.c
  modules/resourceid/CMakeLists.txt
  modules/resourceid/fsw/inc/cfe_resourceid_basevalue.h
  modules/resourceid/fsw/src/cfe_resourceid_api.c
  modules/resourceid/mission_build.cmake
  modules/sb/fsw/src/cfe_sb_priv.h
Labels: IC:2021-04-27
