Repository nasa/cFE, pull requests merged in 2022-01, with the labels that each got.

#2012 Fix #1997, Mismatched foreach in cmake function
  cmake/mission_build.cmake
Labels: CCB:Approved

#2013 Fix #2016, cFE Application Developers Guide.md: specify language for improved code highlighting
  docs/cFE Application Developers Guide.md
Labels: CCB:Approved, docs, community

#2015 Fix #1823, FS Functional test
  modules/cfe_testcase/src/fs_util_test.c
Labels: CCB:Approved

#2023 Fix #2022, Limit SBR UT loops
  modules/sbr/ut-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/ut-coverage/test_cfe_sbr_map_hash.c
Labels: CCB:Approved, Priority: Mission

#2025 Fix #2024, osal_id_t type conversion in es_UT.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#2027 Fix #2026, CFE_FS_ParseInputFileNameEx avoid uninit var
  modules/core_api/ut-stubs/src/cfe_fs_handlers.c
Labels: CCB:Approved

#2029 Fix #2028, Initialize BlockData in ES UT
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#2031 Fix #2030, array length calculation for perf structs
  modules/es/fsw/src/cfe_es_task.c
Labels: CCB:Approved

#2033 Fix #2032, Add CFE_ES_AppInfo_t element documentation
  modules/core_api/fsw/inc/cfe_es_extern_typedefs.h
Labels: CCB:Ready, docs
