Repository nasa/cFE, pull requests merged in 2022-05, with the labels that each got.

#2078 Fix #1097, adds truncation warning suppression flags
  cmake/sample_defs/arch_build_custom.cmake
Labels: CCB:Approved

#2088 Fix #2084, Add support for fractional seconds in epoch
  cmake/sample_defs/sample_mission_cfg.h
  modules/time/fsw/src/cfe_time_api.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#2094 Fix #2092, Doc deploy from local workflow on main branch push
  .github/workflows/build-documentation.yml
Labels: CCB:Approved, dependency

#2099 Fix #2090, UT updates for alternate time configuration
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#2111 cFE Integration candidate: Caelum-rc4+dev10
  README.md
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_counter_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_mempool_test.c
  modules/cfe_testcase/src/es_resource_id_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/cfe_testcase/src/fs_util_test.c
  modules/cfe_testcase/src/resource_id_misc_test.c
  modules/cfe_testcase/src/sb_pipe_mang_test.c
  modules/cfe_testcase/src/sb_sendrecv_test.c
  modules/cfe_testcase/src/sb_subscription_test.c
  modules/cfe_testcase/src/tbl_content_access_test.c
  modules/cfe_testcase/src/tbl_content_mang_test.c
  modules/cfe_testcase/src/tbl_information_test.c
  modules/cfe_testcase/src/tbl_registration_test.c
  modules/core_api/fsw/inc/cfe_version.h
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_backgroundtask.c
  modules/es/fsw/src/cfe_es_start.c
  modules/es/fsw/src/cfe_es_syslog.c
  modules/es/fsw/src/cfe_es_task.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/fsw/src/cfe_evs_utils.c
  modules/evs/ut-coverage/evs_UT.c
  modules/msg/ut-coverage/test_msg_pri_not.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/sb/ut-coverage/sb_UT.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/ut-coverage/tbl_UT.c
  modules/time/fsw/src/cfe_time_utils.c
  modules/time/ut-coverage/time_UT.c
Labels: community

#2105 Fix #2100 #2101 #2102 #2103, Resolve static analysis warnings
  modules/cfe_testcase/src/es_cds_test.c
  modules/cfe_testcase/src/es_counter_test.c
  modules/cfe_testcase/src/es_info_test.c
  modules/cfe_testcase/src/es_mempool_test.c
  modules/cfe_testcase/src/es_resource_id_test.c
  modules/cfe_testcase/src/es_task_test.c
  modules/cfe_testcase/src/fs_header_test.c
  modules/cfe_testcase/src/fs_util_test.c
  modules/cfe_testcase/src/resource_id_misc_test.c
  modules/cfe_testcase/src/sb_pipe_mang_test.c
  modules/cfe_testcase/src/sb_sendrecv_test.c
  modules/cfe_testcase/src/sb_subscription_test.c
  modules/cfe_testcase/src/tbl_content_access_test.c
  modules/cfe_testcase/src/tbl_content_mang_test.c
  modules/cfe_testcase/src/tbl_information_test.c
  modules/cfe_testcase/src/tbl_registration_test.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_backgroundtask.c
  modules/es/fsw/src/cfe_es_start.c
  modules/es/fsw/src/cfe_es_syslog.c
  modules/es/fsw/src/cfe_es_task.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/fsw/src/cfe_evs_utils.c
  modules/evs/ut-coverage/evs_UT.c
  modules/msg/ut-coverage/test_msg_pri_not.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/sb/ut-coverage/sb_UT.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/ut-coverage/tbl_UT.c
  modules/time/fsw/src/cfe_time_utils.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#2108 Fix #2104, cFE_Users_guide.pdf 404
  README.md
Labels: CCB:Ready, CCB:FastTrack
