Repository nasa/cFE, pull requests merged in 2022-12, with the labels that each got.

#2215 Fix #2214, add abstract documentation dependency target
  cmake/mission_build.cmake
Labels: CCB:Approved, dependency

#2217 Fix #2216, update github action versions
  .github/workflows/build-documentation.yml
  .github/workflows/code-coverage.yml
  .github/workflows/functional-tests.yml
Labels: CCB:Approved

#2219 Fix #2218, add -fno-common to arch build flags
  cmake/sample_defs/arch_build_custom_native.cmake
Labels: CCB:Ready, CCB:FastTrack

#2222 Fix #2220, Combine MESSAGE and CMD ENTRY Macros
  modules/tbl/fsw/src/cfe_tbl_task.c
Labels: CCB:Ready, CCB:FastTrack

#2226 Fix #2220, Replace CFE_MSG_CommandHeader_t w/ CFE_TBL_NoArgsCmd_t
  modules/tbl/fsw/src/cfe_tbl_task.c
Labels: CCB:Ready, CCB:FastTrack

#2192 Fix #2174, Move CRC types and convert to enum
  cmake/sample_defs/sample_mission_cfg.h
  docs/cFE Application Developers Guide.md
  modules/cfe_testcase/src/es_misc_test.c
  modules/core_api/fsw/inc/cfe_es.h
  modules/core_api/fsw/inc/cfe_es_api_typedefs.h
  modules/core_api/ut-stubs/src/cfe_es_stubs.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#2229 Fix #2228, Update UTs to use correct cmd types
  modules/es/fsw/inc/cfe_es_msg.h
  modules/es/fsw/src/cfe_es_task.c
  modules/es/fsw/src/cfe_es_task.h
  modules/es/ut-coverage/es_UT.c
  modules/evs/fsw/inc/cfe_evs_msg.h
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/fsw/src/cfe_evs_task.h
  modules/evs/ut-coverage/evs_UT.c
  modules/sb/fsw/inc/cfe_sb_msg.h
  modules/sb/fsw/src/cfe_sb_priv.h
  modules/sb/fsw/src/cfe_sb_task.c
  modules/sb/ut-coverage/sb_UT.c
  modules/tbl/fsw/inc/cfe_tbl_msg.h
  modules/tbl/ut-coverage/tbl_UT.c
  modules/time/fsw/inc/cfe_time_msg.h
  modules/time/fsw/src/cfe_time_task.c
  modules/time/fsw/src/cfe_time_utils.h
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#2231 Fix #2230, EDS Updates to match the current mainline
  modules/cfe_testcase/eds/cfe_testcase.xml
  modules/core_api/eds/base_types.xml
  modules/es/eds/cfe_es.xml
  modules/evs/eds/cfe_evs.xml
  modules/fs/eds/cfe_fs.xml
  modules/resourceid/eds/cfe_resourceid.xml
  modules/sb/eds/cfe_sb.xml
  modules/tbl/eds/cfe_tbl.xml
  modules/time/eds/cfe_time.xml
Labels: CCB:Approved
