Repository nasa/cFE, pull requests merged in 2022-02, with the labels that each got.

#2035 Fix #2034, Update CodeQL workflow
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency, continuous-integration

#2037 Fix #2036, Revert breaking change to CFE_ES_AppInfo_t structure
  docs/src/mnem_maps/cfe_es_tlm_mnem_map
  modules/cfe_testcase/src/es_info_test.c
  modules/core_api/fsw/inc/cfe_es_extern_typedefs.h
  modules/es/eds/cfe_es.xml
  modules/es/fsw/src/cfe_es_apps.c
Labels: CCB:Approved

#2041 Fix #2040, Improve CFE_SB_IsValidMsgId handler
  modules/core_api/ut-stubs/src/cfe_sb_handlers.c
Labels: CCB:Approved

#2042 Fix #2039, Replace CFE_SB_ValueToMsgId(0) with CFE_SB_INVALID_MSG_ID
  modules/cfe_testcase/src/message_id_test.c
  modules/cfe_testcase/src/msg_api_test.c
  modules/msg/ut-coverage/test_cfe_msg_ccsdsext.c
  modules/msg/ut-coverage/test_cfe_msg_init.c
  modules/msg/ut-coverage/test_cfe_msg_msgid_shared.c
  modules/sbr/ut-coverage/test_cfe_sbr_map_direct.c
  modules/sbr/ut-coverage/test_cfe_sbr_map_hash.c
  modules/sbr/ut-coverage/test_cfe_sbr_route_unsorted.c
  modules/tbl/fsw/src/cfe_tbl_task.c
Labels: CCB:Approved, community

#2048 Fix #2047, Add CFE_ES_CreateChildTask default handler
  modules/core_api/ut-stubs/src/cfe_es_handlers.c
  modules/core_api/ut-stubs/src/cfe_es_stubs.c
Labels: CCB:Approved

#2050 Fix #2049, Remove explicit filename doxygen comments
  cmake/target/src/target_config.c
Labels: CCB:Approved

#2052 Fix #2051, Resolve doxygen doc warnings and enforce in CI
  .github/workflows/build-documentation.yml
  cmake/cfe-common.doxyfile.in
  modules/sb/fsw/src/cfe_sb_priv.h
  modules/tbl/fsw/src/cfe_tbl_task.h
Labels: CCB:Approved, dependency

#2056 Fix #2054, Missing SB include for v2 msgid
  modules/msg/fsw/src/cfe_msg_msgid_v2.c
Labels: CCB:Approved
