Repository nasa/cFE, pull requests merged in 2022-10, with the labels that each got.

#2145 Fixes issue #2144- Propagate CMAKE_EXPORT_COMPILE_COMMANDS variable
  cmake/mission_build.cmake
Labels: CCB:Approved

#2148 Fix #2147, Remove CodeQL Paths Ignore
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, continuous-integration

#2151 Fix #1460, Duplicated Logic in CFE_SB_BroadcastBufferToRoute
  modules/sb/fsw/src/cfe_sb_api.c
Labels: CCB:Approved

#2154 Fix #2153, Remove unnecessary parentheses around return values.
  modules/core_api/fsw/inc/cfe_resourceid.h
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_cds.c
  modules/es/fsw/src/cfe_es_cds.h
  modules/es/fsw/src/cfe_es_erlog.c
  modules/es/fsw/src/cfe_es_generic_pool.c
  modules/es/fsw/src/cfe_es_mempool.c
  modules/es/fsw/src/cfe_es_mempool.h
  modules/es/fsw/src/cfe_es_resource.h
  modules/es/fsw/src/cfe_es_syslog.c
  modules/es/fsw/src/cfe_es_task.c
  modules/evs/fsw/src/cfe_evs.c
  modules/evs/fsw/src/cfe_evs_log.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/fsw/src/cfe_evs_utils.c
  modules/evs/fsw/src/cfe_evs_utils.h
  modules/fs/fsw/src/cfe_fs_api.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/time/fsw/src/cfe_time_api.c
  modules/time/fsw/src/cfe_time_task.c
  modules/time/fsw/src/cfe_time_tone.c
  modules/time/fsw/src/cfe_time_utils.c
Labels: CCB:Approved

#2156 Fix #1540, Remove 'return;' from last line of void functions.
  modules/cfe_testcase/src/es_task_test.c
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_cds.c
  modules/evs/fsw/src/cfe_evs_log.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/fs/fsw/src/cfe_fs_priv.c
  modules/sb/fsw/src/cfe_sb_priv.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_task.c
  modules/time/fsw/src/cfe_time_api.c
  modules/time/fsw/src/cfe_time_task.c
  modules/time/fsw/src/cfe_time_tone.c
  modules/time/fsw/src/cfe_time_utils.c
Labels: CCB:Approved

#2158 Fix #2157, Update TO_LAB entry point in cfe_es_startup.scr
  cmake/sample_defs/cpu1_cfe_es_startup.scr
Labels: CCB:Approved

#2159 Fix #782, Create CHANGELOG.md
  CHANGELOG.md
  README.md
Labels: CCB:Approved

#2165 Fix #2164, Remove Changelog in Doxygen Config
  cmake/cfe-common.doxyfile.in
  cmake/mission-doc.doxyfile.in
Labels: CCB:Approved

#2184 Fix #2183, use osal_public_api header targets in doc
  cmake/mission_build.cmake
Labels: CCB:Ready, CCB:FastTrack
