Repository nasa/cFE, pull requests merged in 2023-12, with the labels that each got.

#2466 Fix #2465, add multi threaded SB perf tests
  modules/cfe_testcase/src/sb_performance_test.c
Labels: CCB:Approved

#2468 Fix #2467, message integrity API
  modules/cfe_testcase/src/sb_sendrecv_test.c
  modules/core_api/fsw/inc/cfe_msg.h
  modules/core_api/fsw/inc/cfe_sb.h
  modules/core_api/ut-stubs/src/cfe_msg_handlers.c
  modules/core_api/ut-stubs/src/cfe_msg_stubs.c
  modules/core_api/ut-stubs/src/cfe_sb_stubs.c
  modules/msg/CMakeLists.txt
  modules/msg/fsw/src/cfe_msg_init.c
  modules/msg/fsw/src/cfe_msg_integrity.c
  modules/msg/ut-coverage/CMakeLists.txt
  modules/msg/ut-coverage/msg_UT.c
  modules/msg/ut-coverage/test_cfe_msg_init.c
  modules/msg/ut-coverage/test_cfe_msg_init.h
  modules/msg/ut-coverage/test_cfe_msg_integrity.c
  modules/msg/ut-coverage/test_cfe_msg_verify.c
  modules/msg/ut-coverage/test_cfe_msg_verify.h
  modules/sb/fsw/inc/cfe_sb_eventids.h
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/ut-coverage/sb_UT.c
Labels: CCB:Approved

#2470 Fix #2469, change workflow to use output on failure option
  .github/workflows/code-coverage.yml
Labels: CCB:Approved

#2373 Fix #2372 TBL UT update for OSAL/CFE path length mismatch
  modules/tbl/ut-coverage/tbl_UT.c
Labels: CCB:Approved, Equuleus-rc2

#2409 Fix #2407 Add perfid limit info to ES docstring
  modules/core_api/fsw/inc/cfe_es.h
  modules/es/config/default_cfe_es_interface_cfg.h
Labels: CCB:Approved, docs

#2411 Fix #2410, document ES Perf enums
  modules/es/config/default_cfe_es_msgdefs.h
  modules/es/fsw/src/cfe_es_perf.h
Labels: CCB:Approved, docs

#2472 Fix #2057, Update docs and UT to use `CFE_MSG_PTR`
  docs/cFE Application Developers Guide.md
  modules/cfe_testcase/src/sb_sendrecv_test.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/ut-coverage/evs_UT.c
  modules/sb/ut-coverage/sb_UT.c
  modules/tbl/ut-coverage/tbl_UT.c
  modules/time/fsw/src/cfe_time_tone.c
Labels: CCB:Approved

#2474 Fix #2473, 2475, document and use topicid numbers for cfe
  cmake/arch_build.cmake
  cmake/mission_build.cmake
  cmake/sample_defs/example_platform_cfg.h
  docs/src/cfe_time.dox
  modules/cfe_testcase/config/default_cfe_test_msgids.h
  modules/cfe_testcase/config/default_cfe_test_topicids.h
  modules/cfe_testcase/src/sb_subscription_test.c
  modules/core_api/arch_build.cmake
  modules/core_api/config/default_cfe_core_api_base_msgids.h
  modules/core_api/mission_build.cmake
  modules/es/arch_build.cmake
  modules/es/config/default_cfe_es_msgids.h
  modules/es/config/default_cfe_es_topicids.h
  modules/evs/arch_build.cmake
  modules/evs/config/default_cfe_evs_msgids.h
  modules/evs/config/default_cfe_evs_topicids.h
  modules/evs/ut-coverage/evs_UT.c
  modules/sb/arch_build.cmake
  modules/sb/config/default_cfe_sb_msgids.h
  modules/sb/config/default_cfe_sb_topicids.h
  modules/sb/ut-coverage/sb_UT.h
  modules/tbl/arch_build.cmake
  modules/tbl/config/default_cfe_tbl_msgids.h
  modules/tbl/config/default_cfe_tbl_topicids.h
  modules/time/arch_build.cmake
  modules/time/config/default_cfe_time_fcncodes.h
  modules/time/config/default_cfe_time_internal_cfg.h
  modules/time/config/default_cfe_time_msgids.h
  modules/time/config/default_cfe_time_topicids.h
  modules/time/eds/cfe_time.xml
  modules/time/fsw/inc/cfe_time_eventids.h
  modules/time/fsw/src/cfe_time_dispatch.c
  modules/time/fsw/src/cfe_time_task.c
  modules/time/fsw/src/cfe_time_utils.c
  modules/time/fsw/src/cfe_time_utils.h
  modules/time/fsw/src/cfe_time_verify.h
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#2482 Fix #2481, correct loop variable
  cmake/arch_build.cmake
Labels: CCB:Approved
