Repository nasa/cFE, pull requests merged in 2023-08, with the labels that each got.

#2425 cFE Integration candidate for fast-tracked PRs
  CHANGELOG.md
  cmake/arch_build.cmake
  cmake/tables/elf2cfetbl_rules.mk
  cmake/tables/tabletool_rule.mk
  modules/core_api/fsw/inc/cfe_version.h
Labels: CCB:FastTrack

#2422 Fix #2421, adjust dependencies on table lib
  cmake/arch_build.cmake
Labels: CCB:Ready, CCB:FastTrack

#2424 Fix #2423, avoid use of abspath make function
  cmake/tables/elf2cfetbl_rules.mk
  cmake/tables/tabletool_rule.mk
Labels: CCB:Ready, CCB:FastTrack

#2428 Fix #2427, Race condition in TestCreateChild
  modules/cfe_testcase/src/es_task_test.c
Labels: CCB:Approved

#2431 Fix #2430, reinstate example header files.
  cmake/sample_defs/example_mission_cfg.h
  cmake/sample_defs/example_platform_cfg.h
Labels: CCB:Approved
