Repository nasa/cFE, pull requests merged in 2023-09, with the labels that each got.

#2380 Fix #2379, implement SB bulk transfer test
  modules/cfe_assert/inc/cfe_assert.h
  modules/cfe_assert/src/cfe_assert_runner.c
  modules/cfe_testcase/CMakeLists.txt
  modules/cfe_testcase/src/cfe_test.c
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/sb_performance_test.c
Labels: CCB:Approved, unit-test, Equuleus-rc2

#2401 Fix #2334, Uninitialized PktTime in EVS_SendViaPorts
  modules/evs/fsw/src/cfe_evs_utils.c
Labels: enhancement, CCB:Approved, Equuleus-rc2

#2403 Fix #2402, Uninitialized ExceptionTaskID in CFE_ES_RunExceptionScan
  modules/es/fsw/src/cfe_es_erlog.c
Labels: enhancement, CCB:Approved, Equuleus-rc2

#2420 Fix #2419, Fixes errors in IC Bundle workflow file
  .github/workflows/icbundle.yml
  CHANGELOG.md
Labels: CCB:Approved, continuous-integration, Equuleus-rc2

#2437 Fix #2150, Adds a cast to the negation of unsigned expression
  modules/evs/fsw/src/cfe_evs_utils.c
Labels: enhancement, CCB:Approved
