Repository nasa/cFE, pull requests merged in 2023-06, with the labels that each got.

#2350 Fix #2349, Format update for additional counters in summary
  modules/cfe_assert/src/cfe_assert_io.c
Labels: CCB:Approved, functional

#2354 Fix #2352, make shared tbl configurable
  modules/cfe_testcase/src/cfe_test.h
  modules/cfe_testcase/src/tbl_content_access_test.c
  modules/cfe_testcase/src/tbl_information_test.c
  modules/cfe_testcase/src/tbl_registration_test.c
Labels: CCB:Approved

#2356 fix#2316 - CFE_TIME_Print() calls strftime()
  modules/core_api/fsw/inc/cfe_time.h
  modules/core_api/ut-stubs/src/cfe_time_handlers.c
  modules/core_api/ut-stubs/src/cfe_time_stubs.c
  modules/time/config/default_cfe_time_interface_cfg.h
  modules/time/fsw/src/cfe_time_api.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved

#2361 Fix #2360, Adds utassert message descriptions to README_Functionaltes…
  docs/README_functionaltest.md
Labels: CCB:Approved, docs

#2364 Fix #2363, Increase slp time in funct test workflow
  .github/workflows/functional-tests.yml
Labels: CCB:Approved

#2276 Fix #1515, Remove unnecessary memset from CFE_TBL_LoadFromFile
  modules/tbl/fsw/src/cfe_tbl_internal.c
Labels: CCB:Approved

#2369 Fix #2368, cFE Functional Test 23
  modules/cfe_testcase/src/es_misc_test.c
Labels: bug, CCB:Approved

#2272 Fix #1407, Add error report on EVS failure during log header write
  modules/evs/fsw/inc/cfe_evs_eventids.h
  modules/evs/fsw/src/cfe_evs_log.c
Labels: CCB:Approved

#2389 Fix#2388, Revert "Merge pull request #2356 from CDKnightNASA/fix-2316-time_fmt"
  modules/core_api/fsw/inc/cfe_time.h
  modules/core_api/ut-stubs/src/cfe_time_handlers.c
  modules/core_api/ut-stubs/src/cfe_time_stubs.c
  modules/time/config/default_cfe_time_interface_cfg.h
  modules/time/fsw/src/cfe_time_api.c
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Ready, CCB:FastTrack
