Repository nasa/cFE, pull requests merged in 2024-07, with the labels that each got.

#2344 Fix #2343, Update `CFE_PLATFORM_ES_DEFAULT_SYSLOG_MODE` macro in es_verify.h
  modules/es/fsw/src/cfe_es_verify.h
  modules/tbl/config/default_cfe_tbl_internal_cfg.h
Labels: enhancement, CCB:Approved

#2359 Fix #2116, Update comment re. limits of `CFE_PLATFORM_SB_HIGHEST_VALID_MSGID`
  modules/core_private/config/default_cfe_core_private_internal_cfg.h
  modules/es/config/default_cfe_es_interface_cfg.h
  modules/es/config/default_cfe_es_internal_cfg.h
  modules/es/config/default_cfe_es_mission_cfg.h
  modules/es/config/default_cfe_es_msg.h
  modules/es/config/default_cfe_es_platform_cfg.h
  modules/evs/config/default_cfe_evs_interface_cfg.h
  modules/evs/config/default_cfe_evs_internal_cfg.h
  modules/evs/config/default_cfe_evs_mission_cfg.h
  modules/evs/config/default_cfe_evs_msg.h
  modules/evs/config/default_cfe_evs_platform_cfg.h
  modules/fs/config/default_cfe_fs_mission_cfg.h
  modules/sb/config/default_cfe_sb_fcncodes.h
  modules/sb/config/default_cfe_sb_interface_cfg.h
  modules/sb/config/default_cfe_sb_internal_cfg.h
  modules/sb/config/default_cfe_sb_mission_cfg.h
  modules/sb/config/default_cfe_sb_msg.h
  modules/sb/config/default_cfe_sb_msgdefs.h
  modules/sb/config/default_cfe_sb_msgids.h
  modules/sb/config/default_cfe_sb_msgstruct.h
  modules/sb/config/default_cfe_sb_platform_cfg.h
  modules/sb/config/default_cfe_sb_topicids.h
  modules/tbl/config/default_cfe_tbl_interface_cfg.h
  modules/tbl/config/default_cfe_tbl_internal_cfg.h
  modules/tbl/config/default_cfe_tbl_mission_cfg.h
  modules/tbl/config/default_cfe_tbl_msg.h
  modules/tbl/config/default_cfe_tbl_platform_cfg.h
  modules/time/config/default_cfe_time_interface_cfg.h
  modules/time/config/default_cfe_time_internal_cfg.h
  modules/time/config/default_cfe_time_mission_cfg.h
  modules/time/config/default_cfe_time_msg.h
  modules/time/config/default_cfe_time_platform_cfg.h
Labels: CCB:Approved

#2376 Fix #2375, Use `size_t` for variables/parameters representing size
  modules/cfe_testcase/src/tbl_content_mang_test.c
  modules/core_api/ut-stubs/src/cfe_sb_handlers.c
  modules/core_private/ut-stubs/inc/ut_support.h
  modules/core_private/ut-stubs/src/ut_support.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_start.h
  modules/es/fsw/src/cfe_es_task.c
  modules/es/ut-coverage/es_UT.c
  modules/evs/ut-coverage/evs_UT.c
  modules/sb/fsw/src/cfe_sb_task.c
  modules/sb/ut-coverage/sb_UT.c
  modules/tbl/ut-coverage/tbl_UT.c
Labels: enhancement, CCB:Approved

#2381 Fix #2378, refactor SB to support additional use cases
  .github/workflows/code-coverage.yml
  modules/sb/fsw/src/cfe_sb_api.c
  modules/sb/fsw/src/cfe_sb_buf.c
  modules/sb/fsw/src/cfe_sb_priv.c
  modules/sb/fsw/src/cfe_sb_priv.h
  modules/sb/ut-coverage/sb_UT.c
  modules/sb/ut-coverage/sb_UT.h
Labels: enhancement, CCB:Provisionally-Approved

#2496 Fix #2495, Remove superfluous status assignment in `CFE_SB_CreatePipe`
  modules/sb/fsw/src/cfe_sb_api.c
Labels: CCB:Approved

#2551 Fix #2550, use resourceids for internal table validation and dump control blocks
  modules/resourceid/fsw/inc/cfe_core_resourceid_basevalues.h
  modules/tbl/fsw/src/cfe_tbl_api.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_internal.h
  modules/tbl/fsw/src/cfe_tbl_resource.c
  modules/tbl/fsw/src/cfe_tbl_resource.h
  modules/tbl/fsw/src/cfe_tbl_task.h
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/fsw/src/cfe_tbl_transaction.c
  modules/tbl/fsw/src/cfe_tbl_transaction.h
  modules/tbl/ut-coverage/tbl_UT.c
  modules/tbl/ut-coverage/tbl_UT.h
Labels: CCB:Provisionally-Approved

#2554 Fix #2553, null value in vsnprintf
  modules/es/ut-coverage/es_UT.c
Labels: CCB:Approved

#2560 Fix #2559, Improve CFE_SB_AllocateMessageBuffer error report
  modules/sb/fsw/src/cfe_sb_api.c
Labels: CCB:Approved

#2566 Fix #2529, Reduces CFE_EVS_MAX_PORT_MSG_LENGTH to prevent new line character truncation
  modules/evs/fsw/src/cfe_evs_task.h
Labels: bug, CCB:Approved

#2573 Fix 2572, CFE_TIME unit test failure when CFE_MISSION_TIME_AT_TONE_WI…
  modules/time/ut-coverage/time_UT.c
Labels: CCB:Approved
