Repository nasa/cFE, pull requests merged in 2024-03, with the labels that each got.

#2527 Hotfix #2526, add missing memset() for stack variables
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_task.c
Labels: CCB:Ready, CCB:FastTrack

#2517 Fix #2516, propagate stack pointer for child tasks
  modules/cfe_testcase/src/es_task_test.c
  modules/core_api/fsw/inc/cfe_version.h
  modules/es/fsw/src/cfe_es_api.c
  modules/es/fsw/src/cfe_es_apps.c
  modules/es/fsw/src/cfe_es_apps.h
Labels: CCB:Approved

#2387 Fix #2386, Split up and simplify control flow in `CFE_TBL_Register()`
  modules/tbl/fsw/src/cfe_tbl_api.c
  modules/tbl/fsw/src/cfe_tbl_internal.c
  modules/tbl/fsw/src/cfe_tbl_internal.h
  modules/tbl/ut-coverage/tbl_UT.c
Labels: enhancement, CCB:Approved

#2531 Fix #2530, naming convention for SendHkCmd
  modules/es/fsw/src/cfe_es_dispatch.c
  modules/es/fsw/src/cfe_es_task.c
  modules/es/fsw/src/cfe_es_task.h
  modules/evs/fsw/src/cfe_evs_dispatch.c
  modules/evs/fsw/src/cfe_evs_task.c
  modules/evs/fsw/src/cfe_evs_task.h
  modules/evs/ut-coverage/evs_UT.c
  modules/tbl/fsw/src/cfe_tbl_dispatch.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.c
  modules/tbl/fsw/src/cfe_tbl_task_cmds.h
  modules/tbl/ut-coverage/tbl_UT.c
  modules/tbl/ut-coverage/tbl_UT.h
Labels: CCB:Approved
