Repository nasa/cFE, pull requests merged in 2024-08, with the labels that each got.

#2326 Fix #1432, Add element to write error event in `CFE_EVS_WriteAppDataFileCmd()`
  modules/evs/fsw/src/cfe_evs_task.c
Labels: enhancement, CCB:Approved

#2565 Fix #2564, add config tool for platform-specific settings
  .github/workflows/code-coverage.yml
  cmake/mission_build.cmake
  modules/config/CMakeLists.txt
  modules/config/cmake/cfe_config_ids.h.in
  modules/config/cmake/cfe_config_map.c.in
  modules/config/cmake/cfe_configid_nametable.c.in
  modules/config/cmake/cfe_configid_offset.h.in
  modules/config/cmake/cfe_platform_cfg.c.in
  modules/config/cmake/create_cfe_platform_cfg.cmake
  modules/config/config_ids_base.cmake
  modules/config/fsw/inc/cfe_config_external.h
  modules/config/fsw/inc/cfe_config_init.h
  modules/config/fsw/inc/cfe_config_lookup.h
  modules/config/fsw/inc/cfe_config_nametable.h
  modules/config/fsw/inc/cfe_config_set.h
  modules/config/fsw/inc/cfe_config_table.h
  modules/config/fsw/src/cfe_config_get.c
  modules/config/fsw/src/cfe_config_init.c
  modules/config/fsw/src/cfe_config_priv.h
  modules/config/fsw/src/cfe_config_set.c
  modules/config/mission_build.cmake
  modules/config/tool/CMakeLists.txt
  modules/config/tool/cfeconfig_platformdata_table.c
  modules/config/tool/cfeconfig_platformdata_tool.c
  modules/config/tool/cfeconfig_platformdata_tool.h
  modules/config/tool/cmake/cfe_platform_list.c.in
  modules/config/tool/config_ids_dynamic.cmake
  modules/config/ut-coverage/CMakeLists.txt
  modules/config/ut-coverage/test_cfe_config.c
  modules/config/ut-coverage/ut-stubs/cfe_config_external_stubs.c
  modules/config/ut-coverage/ut-stubs/cfe_config_init_stubs.c
  modules/config/ut-coverage/ut-stubs/cfe_config_lookup_stubs.c
  modules/config/ut-coverage/ut-stubs/cfe_config_set_stubs.c
  modules/core_api/fsw/inc/cfe_config.h
  modules/core_api/fsw/inc/cfe_config_api_typedefs.h
  modules/core_api/ut-stubs/src/cfe_config_stubs.c
Labels: CCB:Approved

#2579 Fix #2576, Runtime Error in coverage-es-ALL, TestApps
  modules/es/fsw/src/cfe_es_apps.c
Labels: CCB:Approved

#2584 Fix #2581, Adding bytes read check
  modules/fs/fsw/src/cfe_fs_api.c
  modules/fs/ut-coverage/fs_UT.c
Labels: CCB:Approved

#2585 Fix #2582, Cast to unsigned int
  modules/msg/fsw/src/cfe_msg_sechdr_time.c
Labels: CCB:Approved

#2586 Fix #2116, Update comment re. limit of `CFE_PLATFORM_SB_HIGHEST_VALID_MSGID`
  cmake/sample_defs/example_platform_cfg.h
Labels: CCB:Approved, docs

#2591 Fix #2590, Use proper printf format for size_t
  modules/sb/fsw/src/cfe_sb_api.c
Labels: CCB:Approved

#2593 Fix #2592, Yield cpu to other tasks in SB Perf Test
  modules/cfe_testcase/src/sb_performance_test.c
Labels: CCB:Approved

#2596 Fix #2595, Use string append and add newline
  modules/config/tool/CMakeLists.txt
Labels: CCB:Approved
